# https://ku.wiktionary.org/wiki/Alîkarî:Cureyên_peyvan
POS_DATA = {
    "Navdêr": {"pos": "noun"},
    "Serenav": {"pos": "name"},
    "Lêker": {"pos": "verb"},
    "Rengdêr": {"pos": "adj"},
    "Hoker": {"pos": "adv"},
    "Cînav": {"pos": "pron"},
    "Baneşan": {"pos": "intj"},
    "Daçek": {"pos": "prep"},
    "Pêşdaçek": {"pos": "prep"},
    "Paşdaçek": {"pos": "postp"},
    "Bazinedaçek": {"pos": "circumpos"},
    "Girêdek": {"pos": "conj"},
    "Artîkel": {"pos": "article"},
    "Pirtik": {"pos": "article"},
    "Navgir": {"pos": "infix", "tags": ["morpheme"]},
    "Paşgir": {"pos": "suffix", "tags": ["morpheme"]},
    "Pêşgir": {"pos": "prefix", "tags": ["morpheme"]},
    "Reh": {"pos": "root", "tags": ["morpheme"]},
    "Rehekî lêkerê": {"pos": "root", "tags": ["morpheme"]},
    "Biwêj": {"pos": "phrase", "tags": ["idiomatic"]},
    "Hevok": {"pos": "phrase"},
    "Gotineke pêşiyan": {"pos": "proverb"},
    "Hejmar": {"pos": "num", "tags": ["number"]},
    "Tîp": {"pos": "character", "tags": ["letter"]},
    "Sembol": {"pos": "symbol"},
    "Kurtenav": {"pos": "abbrev", "tags": ["abbreviation"]},
    "Formeke navdêrê": {"pos": "noun", "tags": ["form-of"]},
    "Formeke lêkerê": {"pos": "verb", "tags": ["form-of"]},
    "Formeke rengdêrê": {"pos": "adj", "tags": ["form-of"]},
    "Formeke cînavê": {"pos": "pron", "tags": ["form-of"]},
    "Formeke hokerê": {"pos": "adv", "tags": ["form-of"]},
    "Formeke serenavê": {"pos": "name", "tags": ["form-of"]},
    "Mane": {"pos": "unknown"},
}

LINKAGE_SECTIONS = {
    "Hevmane": "synonyms",
    "Dijmane": "antonyms",
    "Jê": "derived",
    "Nêzîk": "synonyms",
    "Têkildar": "related",
    "Jornav": "hypernyms",
    "Jêrnav": "hyponyms",
    "Anagram": "anagrams",
    "Binêre herwiha": "synonyms",
    "Qafiye": "rhymes",
    "Navê zanistî": "related",
    "Têkilî": "related",
    "Bide Ber": "related",
    "Binere herwiha": "synonyms",
    "Demên din": "synonyms",
    "Kurtenav": "abbreviations",
    "Sembol": "synonyms",
    "Biwêj": "related",
}

LINKAGE_TAGS = {
    "Navê zanistî": ["Scientific-Latin"],
    "Sembol": ["symbol"],
    "Biwêj": ["idiomatic"],
}
