POS_DATA = {
    "podstatné jméno": {"pos": "noun"},
    "přídavné jméno": {"pos": "adj"},
    "zájmeno": {"pos": "pron"},
    "číslovka": {"pos": "num"},
    "sloveso": {"pos": "verb"},
    "příslovce": {"pos": "adv"},
    "předložka": {"pos": "prep"},
    "spojka": {"pos": "conj"},
    "částice": {"pos": "particle"},
    "citoslovce": {"pos": "intj"},
    "záložka": {"pos": "unknown"},
    "člen": {"pos": "article"},
    "klasifikátor": {"pos": "classifier"},
    "predikativ": {"pos": "adj", "tags": ["predicative"]},
    "enklitikon": {"pos": "suffix", "tags": ["clitic"]},
    "copula": {"pos": "unknown"},
    "ukazatel existence": {"pos": "unknown"},
    "honorifikum": {"pos": "unknown"},
    "konektor": {"pos": "unknown"},
    "substitut": {"pos": "unknown"},
    "slovní spojení": {"pos": "phrase"},
    "fráze": {"pos": "phrase"},
    "rčení": {"pos": "phrase"},
    "úsloví": {"pos": "phrase"},
    "idiom": {"pos": "phrase", "tags": ["idiomatic"]},
    "přísloví": {"pos": "proverb"},
    "zkratka": {"pos": "abbrev", "tags": ["abbreviation"]},
    "předpona": {"pos": "prefix", "tags": ["morpheme"]},
    "přípona": {"pos": "suffix", "tags": ["morpheme"]},
    "číslo": {"pos": "num", "tags": ["number"]},
    "značka": {"pos": "symbol"},
    "symbol": {"pos": "symbol"},
    "nevokalizovaný zápis": {"pos": "unknown"},
    "písmeno": {"pos": "character", "tags": ["letter"]},
    "vlastní jméno": {"pos": "name"},
    "stažený tvar": {"pos": "contraction", "tags": ["contraction"]},
    "tvar slovesa": {"pos": "verb", "tags": ["form-of"]},
    "kořen": {"pos": "root", "tags": ["morpheme"]},
    "pořekadlo": {"pos": "phrase", "tags": ["idiomatic"]},
    "partikule": {"pos": "particle"},
    "pseudosloveso": {"pos": "verb"},
    "výraz": {"pos": "phrase", "tags": ["idiomatic"]},
}

LINKAGE_SECTIONS = {
    "synonyma": "synonyms",
    "antonyma": "antonyms",
    "související": "related",
    "slovní spojení": "phrases",
    "fráze a idiomy": "related",
    "přísloví, úsloví a pořekadla": "proverbs",
    "přísloví, rčení a pořekadla": "proverbs",
    "přísloví": "proverbs",
    "fráze": "phrases",
    "odvozené tvary": "derived",
    "příbuzné výrazy": "related",
    "související symboly": "related",
    "významově související": "related",
    "zkratka": "abbreviations",
    "idiomy a fráze": "phrases",
}
