POS_DATA = {
    "podstatné jméno": {"pos": "noun"},
    "přídavné jméno": {"pos": "adj"},
    "zájmeno": {"pos": "pron"},
    "číslovka": {"pos": "num"},
    "sloveso": {"pos": "verb"},
    "příslovce": {"pos": "adv"},
    "předložka": {"pos": "prep"},
    "spojka": {"pos": "conj"},
    "částice": {"pos": "particle"},
    "citoslovce": {"pos": "intj"},
    "záložka": {"pos": "unknown"},
    "člen": {"pos": "article"},
    "klasifikátor": {"pos": "classifier"},
    "predikativ": {"pos": "adj", "tags": ["predicative"]},
    "enklitikon": {"pos": "suffix", "tags": ["clitic"]},
    "copula": {"pos": "unknown"},
    "ukazatel existence": {"pos": "unknown"},
    "honorifikum": {"pos": "unknown"},
    "konektor": {"pos": "unknown"},
    "substitut": {"pos": "unknown"},
    "slovní spojení": {"pos": "phrase"},
    "fráze": {"pos": "phrase"},
    "idiom": {"pos": "phrase", "tags": ["idiomatic"]},
    "přísloví": {"pos": "proverb"},
    "zkratka": {"pos": "abbrev", "tags": ["abbreviation"]},
    "předpona": {"pos": "prefix", "tags": ["morpheme"]},
    "přípona": {"pos": "suffix", "tags": ["morpheme"]},
    "číslo": {"pos": "num", "tags": ["number"]},
    "značka": {"pos": "symbol"},
    "symbol": {"pos": "symbol"},
}

LINKAGE_SECTIONS = {
    "synonyma": "synonyms",
    "antonyma": "antonyms",
    "související": "related",
    "slovní spojení": "phrases",
    "fráze a idiomy": "related",
    "přísloví, úsloví a pořekadla": "proverbs",
    "přísloví, rčení a pořekadla": "proverbs",
}
