POS_DATA = {
    "takrifan": {"pos": "unknown"},
    "kata nama": {"pos": "noun"},
    "kata kerja": {"pos": "verb"},
    "kata ganti nama": {"pos": "pron"},
    "kata hubung": {"pos": "conj"},
    "kata keterangan": {"pos": "adv"},
    "kata sifat": {"pos": "adj"},
    "adverba": {"pos": "adv"},
    "kata penghubung": {"pos": "conj"},
    "aksara han": {"pos": "character", "tags": ["han"]},
    "kanji": {"pos": "character", "tags": ["kanji"]},
    "hanja": {"pos": "character", "tags": ["Hanja"]},
    "hanzi": {"pos": "character", "tags": ["hanzi"]},
    "kata depan": {"pos": "prep"},
    "kata seru": {"pos": "intj"},
    "kata tugas": {"pos": "unknown"},
    "perumian": {"pos": "romanization"},
    "akhiran": {"pos": "suffix", "tags": ["morpheme"]},
    "kata bilangan": {"pos": "num", "tags": ["number"]},
    "kata imbuhan akhir": {"pos": "suffix", "tags": ["morpheme"]},
    "awalan": {"pos": "prefix", "tags": ["morpheme"]},
    "kata imbuhan": {"pos": "prefix", "tags": ["morpheme"]},
    "simbol": {"pos": "symbol"},
    "kata nama khas": {"pos": "name"},
    "kata tanya": {"pos": "pron", "tags": ["interrogative"]},
    "kata adjektif": {"pos": "adj"},
    "singkatan": {"pos": "abbrev", "tags": ["abbreviation"]},
    "kata ganda": {"pos": "noun", "tags": ["plural"]},
    "kata benda": {"pos": "noun"},
    "kata nama am": {"pos": "noun"},
    "peribahasa": {"pos": "proverb"},
    "frasa": {"pos": "phrase"},
    "kata sendi nama": {"pos": "noun"},
    "suku kata": {"pos": "syllable"},
    "penjodoh bilangan": {"pos": "classifier"},
}

FORM_SECTIONS = {
    "tulisan jawi": ["Jawi"],
    "tulisan rumi": ["Rumi"],
    "aksara jawa": ["Javanese"],
    "bentuk alternatif": ["alt-of"],
    "tulisan jawa": ["Javanese"],
}

LINKAGE_SECTIONS = {
    "sinonim": "synonyms",
    "antonim": "antonyms",
    "terbitan": "derived",
    "kata majmuk": "derived",
    "kata terbitan": "derived",
    "anagram": "anagrams",
    "terbitan kata": "derived",
    "peribahasa": "proverbs",
    "istilah berkaitan": "related",
}
