POS_DATA = {
    "Takrifan": {"pos": "unknown"},
    "Kata nama": {"pos": "noun"},
    "Kata kerja": {"pos": "verb"},
    "Kata ganti nama": {"pos": "pron"},
    "Kata hubung": {"pos": "conj"},
    "Kata keterangan": {"pos": "adv"},
    "Kata sifat": {"pos": "adj"},
    "Adverba": {"pos": "adv"},
    "Kata penghubung": {"pos": "conj"},
    "Aksara Han": {"pos": "character", "tags": ["han"]},
    "Kanji": {"pos": "character", "tags": ["kanji"]},
    "Hanja": {"pos": "character", "tags": ["Hanja"]},
    "Hanzi": {"pos": "character", "tags": ["hanzi"]},
    "Kata depan": {"pos": "prep"},
    "Kata seru": {"pos": "intj"},
    "Kata tugas": {"pos": "unknown"},
    "Perumian": {"pos": "romanization"},
    "Akhiran": {"pos": "suffix", "tags": ["morpheme"]},
    "Kata bilangan": {"pos": "num", "tags": ["number"]},
    "Kata imbuhan akhir": {"pos": "suffix", "tags": ["morpheme"]},
    "Awalan": {"pos": "prefix", "tags": ["morpheme"]},
    "Kata imbuhan": {"pos": "prefix", "tags": ["morpheme"]},
    "Simbol": {"pos": "symbol"},
    "Kata nama khas": {"pos": "name"},
    "Kata Tanya": {"pos": "pron", "tags": ["interrogative"]},
    "Kata tanya": {"pos": "pron", "tags": ["interrogative"]},
    "Kata adjektif": {"pos": "adj"},
    "Kata Adjektif": {"pos": "adj"},
    "Singkatan": {"pos": "abbrev", "tags": ["abbreviation"]},
    "Kata ganda": {"pos": "noun", "tags": ["plural"]},
    "Kata benda": {"pos": "noun"},
}

FORM_SECTIONS = {
    "Tulisan Jawi": ["Jawi"],
    "Tulisan Rumi": ["Rumi"],
    "Aksara Jawa": ["Javanese"],
    "Bentuk alternatif": ["alt-of"],
}

LINKAGE_SECTIONS = {
    "Sinonim": "synonyms",
    "Antonim": "antonyms",
    "Terbitan": "derived",
    "Kata majmuk": "derived",
    "Anagram": "anagrams",
}
