POS_DATA = {
    "Takrifan": {"pos": "unknown"},
    "Kata nama": {"pos": "noun"},
    "Kata kerja": {"pos": "verb"},
    "Kata ganti nama": {"pos": "pron"},
    "Kata hubung": {"pos": "conj"},
    "Kata keterangan": {"pos": "adv"},
    "Kata sifat": {"pos": "adj"},
    "Adverba": {"pos": "adv"},
    "Kata penghubung": {"pos": "conj"},
    "Aksara Han": {"pos": "character", "tags": ["han"]},
    "Kanji": {"pos": "character", "tags": ["kanji"]},
    "Hanja": {"pos": "character", "tags": ["Hanja"]},
    "Hanzi": {"pos": "character", "tags": ["hanzi"]},
    "Kata depan": {"pos": "prep"},
    "Kata seru": {"pos": "intj"},
    "Kata tugas": {"pos": "unknown"},
}
