POS_DATA = {
    "Danh từ": {"pos": "noun"},
    "Động từ": {"pos": "verb"},
    "Tính từ": {"pos": "adj"},
    "Định nghĩa": {"pos": "unknown"},
    "Yếu tố": {"pos": "unknown"},
    "Phó từ": {"pos": "adv"},
    "Phụ tố": {"pos": "affix"},
    "Mạo từ": {"pos": "article"},
    "Trợ động từ": {"pos": "verb", "tags": ["auxiliary"]},
    "Phụ tố chu vi": {"pos": "circumfix", "tags": ["morpheme"]},
    "Yếu tố quanh": {"pos": "circumpos"},
    "Từ ghép": {"pos": "suffix", "tags": ["clitic"]},
    "cmavo": {"pos": "unknown"},
    "Liên từ": {"pos": "conj"},
    "Từ rút gọn": {"pos": "contraction", "tags": ["contraction"]},
    "Mạo từ hạn định": {"pos": "article", "tags": ["definitive"]},
    "Tính từ chỉ định": {"pos": "adj", "tags": ["demonstrative"]},
    "Đại từ chỉ định": {"pos": "pron", "tags": ["demonstrative"]},
    "Từ hạn định": {"pos": "det"},
    "Từ ghép sau": {"pos": "suffix", "tags": ["clitic"]},
    "Tên người": {"pos": "name"},
    "Hanja": {"pos": "character", "tags": ["Hanja"]},
    "Chữ tượng hình": {"pos": "character", "tags": ["logogram"]},
    "Thành ngữ": {"pos": "phrase", "tags": ["idiomatic"]},
    "Động từ không ngôi": {"pos": "verb", "tags": ["impersonal"]},
    "Mạo từ bất định": {"pos": "article", "tags": ["indefinite"]},
    "Trung tố": {"pos": "infix", "tags": ["morpheme"]},
    "Thán từ": {"pos": "intj"},
    "Từ nghi vấn": {"pos": "unknown"},
    "Nội động từ": {"pos": "verb", "tags": ["intransitive"]},
    "Kanji": {"pos": "character", "tags": ["kanji"]},
    "Tên": {"pos": "name"},
    "Số từ": {"pos": "num", "tags": ["number"]},
    "Trợ từ": {"pos": "particle"},
    "Động tính từ": {"pos": "adj", "tags": ["particle"]},
    "Mạo từ bộ phận": {"pos": "article", "tags": ["particle"]},
    "Đại từ nhân xưng": {"pos": "pron", "tags": ["particle"]},
    "Địa danh": {"pos": "name", "tags": ["place"]},
    "Tính từ sở hữu": {"pos": "adj", "tags": ["possessive"]},
    "Yếu tố sau": {"pos": "postp"},
    "Tính từ riêng": {"pos": "adj"},
    "Danh từ riêng": {"pos": "name"},
    "Tiền tố": {"pos": "prefix", "tags": ["morpheme"]},
    "Đại từ": {"pos": "pron"},
    "Tục ngữ": {"pos": "proverb"},
    "Dấu câu": {"pos": "punct", "tags": ["punctuation"]},
    "rafsi": {"pos": "unknown"},
    "Đại từ phản thân": {"pos": "pron", "tags": ["reflexive"]},
    "Động từ phản thân": {"pos": "verb", "tags": ["reflexive"]},
    "Đại từ quan hệ": {"pos": "pron", "tags": ["relative"]},
    "Latinh hóa": {"pos": "romanization"},
    "Thân từ": {"pos": "stem"},
    "Hậu tố": {"pos": "suffix", "tags": ["morpheme"]},
    "Ngoại động từ": {"pos": "verb", "tags": ["transitive"]},
}

LINKAGE_SECTIONS = {
    "Từ tương tự": "related",
    "Từ đảo chữ": "anagrams",
    "Trái nghĩa": "antonymous",
    "Từ ghép": "derived",  # compound
    "Từ dẫn xuất": "derived",
    "Phương ngữ khác": "related",  # other dialects
    "Thành ngữ": "related",  # idioms
    "Từ liên hệ": "related",
    "Xem thêm": "related",
    "Đồng nghĩa": "synonyms",
    "Từ phái sinh": "derived",
}


TRANSLATION_SECTIONS = frozenset(["Dịch", "Bản dịch"])
