from .models import WordEntry

# https://vi.wiktionary.org/wiki/Mô_đun:labels/data
LABEL_TAGS = {
    "viết tắt": "abbreviation",
    "trừu tượng": "abstract-noun",
    "acronym": "acronym",
    "ngoại động từ, nội động từ": "ambitransitive",
    "archaic": "archaic",
    "thuộc ngữ": "attributive",
    "attributively": "attributively",
    "trợ động từ": "auxiliary",
    "giống chung": "common",
    "đếm được": "countable",
    "ngoại động từ kép": "ditransitive",
    "khiển cách": "ergative",
    "nghĩa mở rộng": "broadly",
    "thành ngữ tính": "idiomatic",
    "ở dạng số nhiều": "plural",
    "viết tắt từ chữ đầu với cách đọc ghép âm": "initialism",
    "nội động từ": "intransitive",
    "không so sánh được": "not-comparable",
    "tượng thanh": "onomatopoeic",
    "chỉ có số nhiều": "plural-only",
    "tính từ quan hệ": "relational",
    "động từ tĩnh": "stative",
    "ngoại động từ": "transitive",
    "từ láy": "reduplication",
    "không đếm được": "uncountable",
    "cổ xưa": "archaic",
    "ngôn ngữ trẻ con": "childish",
    "vietnamese chữ Nôm": "Chữ-Nôm",
    "từ lóng có vần điệu của người Luân Đôn": ["Cockney", "slang"],
    "thông tục": "colloquial",
    "lỗi thời": "dated",
    "nghĩa xấu": "derogatory",
    "phương ngữ": "dialectal",
    "thuộc phương ngữ": "dialectal",
    "xúc phạm dân tộc": ["ethnic", "slang"],
    "uyển ngữ": "euphemistic",
    "thân mật": "familiar",
    "nghĩa bóng": "figuratively",
    "trang trọng": "formal",
    "từ lóng người đồng tính": "slang",
    "từ ngữ lịch sử": "historical",
    "kính ngữ": "honorific",
    "hài hước": "humorous",
    "không trang trọng": "informal",
    "từ lóng internet": ["Internet", "slang"],
    "trớ trêu": "ironic",
    "nghĩa đen": "literally",
    "ăn chương": "literary",
    "hoán dụ": "metonymically",
    "từ lóng quân sự": "slang",
    "từ mới": "neologism",
    "không còn phát sinh từ mới": "idiomatic",
    "từ tạo ra cho trường hợp cụ thể": "nonce-word",
    "không tiêu chuẩn": "nonstandard",
    "không còn dùng": "obsolete",
    "thuật ngữ không còn dùng": "obsolete",
    "xúc phạm": "offensive",
    "thơ ca": "poetic",
    "lịch sự": "polite",
    "hiếm": "rare",
    "từ lóng": "slang",
    "nhắn tin": "Internet",
    "không phổ biến": "uncommon",
    "thô tục": "vulgar",
    "anh": "UK",
    "biệt ngữ": "jargon",
    "cũ": "obsolete",
    "cổ": "archaic",
    "không dịch": "not-translated",
    "khẩu ngữ": "colloquial",
    "lóng": "slang",
    "mỉa mai": "ironic",
    "nghĩa rộng": "broadly",
    "số nhiều": "plural",
    "nói trại": "euphemistic",
    "tục tĩu": "vulgar",
    "ít dùng": "rare",
    "địa phương": "regional",
    "định ngữ": "attributive",
    "ấn độ": "India",
    "động từ và ngoại động từ": "ambitransitive",
    "châu mỹ": "US",
    "hoa kỳ": "US",
    "phát âm mỹ": "US",
    "hoạt hình": "animate",
    "phương ngữ mắt": "pronunciation-spelling",
    "hy lạp cổ đại": "Ancient-Greek",
    "la mã cổ đại": "Ancient-Rome",
    "luật pháp hoa kỳ": "US",
    "luật pháp việt nam": "Vietnam",
    "chính trị úc": "Australian",
    "chính trị philippines": "Philippine",
    "tu từ học": "rhetoric",
    # Template:zh-forms
    "phồn.": "Traditional-Chinese",
    "giản.": "Simplified-Chinese",
    "alternative forms": "alternative",
    "dated abbreviation": ["dated", "abbreviation"],
    "triều châu": "Teochew",
    "tiếng mân": "Min",
}

# https://vi.wiktionary.org/wiki/Mô_đun:gender_and_number/data
GENDER_NUMBER_TAGS = {
    "giống đực": "masculine",
    "giống cái": "feminine",
    "giống trung": "neuter",
    "giống chung": "common-gender",
    "gender-neutral": "neuter",
    "động vật": "animate",
    "bất động vật": "inanimate",
    "chỉ loài vật": "animal-not-person",
    "từ chỉ cá nhân": "person",
    "nonpersonal": "impersonal",
    "virile (= masculine personal)": "virile",
    "nonvirile (= other than masculine personal)": "nonvirile",
    "số ít": "singular",
    "số kép": "dual",
    "số nhiều": "plural",
    "thể chưa hoàn thành": "imperfective",
    "thể hoàn thành": "perfective",
    "không đổi": "invariable",
}

LOCATIONS = {
    "hà nội": "Hà-Nội",
    "huế": "Huế",
    "sài gòn": "Saigon",
    "vinh": "Vinh",
    "thanh chương": "Thanh-Chương",
    "hà tĩnh": "Hà-Tĩnh",
}

SOUND_TAGS = {
    "phát âm giọng anh chuẩn": "Received-Pronunciation",
    "anh mỹ thông dụng": "General-American",
}

ZH_X_TAGS = {
    "tiêu chuẩn hiện đại": "Standard-Chinese",
    "bính âm": "Pinyin",
    "cantonese": "Cantonese",
    "mandarin": "Mandarin",
}

ZH_PRON_TAGS = {
    "quan thoại": "Mandarin",
    "tiêu chuẩn": "Standard",
    "bính âm hán ngữ": "Pinyin",
    "chú âm phù hiệu": "Bopomofo",
    "xi'an": "Xi'an",
    "guanzhong pinyin": ["Guanzhong", "Pinyin"],
    "đông can": "Dungan",
    "chữ kirin": "Cyrillic",
    "wiktionary": "Wiktionary",
    "quảng đông": "Guanzhong",
    "việt bính": "Jyutping",
    "khách gia": "Hakka",
    "sixian": "Sixian",
    "pfs": "Phak-fa-su",
    "mai huyện": "Meixian",
    "mân bắc": "Min-Bei",
    "kcr": "Kienning-Colloquial-Romanized",
    "mân đông": "Min-Dong",
    "buc": "Foochow-Romanized",
    "mân nam": "Min-Nan",
    "mân tuyền chương": "Hokkien",
    "poj": "POJ",
    "triều châu": "Teochew",
    "peng'im": "Peng'im",
    "hán ngữ tiêu chuẩn": "Standard-Chinese",
    "bính âm thông dụng": "Tongyong-Pinyin",
    "wade–giles": "Wade-Giles",
    "yale": "Yale",
    "quốc ngữ la mã tự": "Gwoyeu-Romatsyh",
    "palladius": "Palladius",
    "ipa hán học": "Sinological-IPA",
    "quảng đông tiêu chuẩn": "Standard-Cantonese",
    "quảng châu–hồng kông": ["Guangzhou", "Hong Kong"],
    "bính âm tiếng quảng đông": ["Cantonese", "Pinyin"],
    "latinh hóa tiếng quảng đông": "Guangdong-Romanization",
    "miền bắc sixian": ["Northern", "Sixian"],
    "miêu lật": "Miaoli",
    "pha̍k-fa-sṳ": "Phak-fa-su",
    "hệ thống la mã hóa tiếng khách gia": "Hakka-Romanization-System",
    "bính âm tiếng khách gia": "Hagfa-Pinyim",
    "miền nam sixian": ["Southern", "Sixian"],
    "mỹ nùng": "Neipu",
    "kiến âu": "Jian'ou",
    "la mã hóa phương ngữ kiến ninh": "Kienning-Colloquial-Romanized",
    "phúc châu": "Fuzhou",
    "bàng-uâ-cê": "Foochow-Romanized",
    "hạ môn": "Xiamen",
    "chương châu": "Zhangzhou",
    "cao hùng": "Kaohsiung",
    "phiên âm bạch thoại": "POJ",
    "tâi-lô": "Tai-lo",
    "phofsit daibuun": "Phofsit-Daibuun",
    "jinjiang": "Jinjiang",
    "philippines": "Philippines",
    "tuyền châu": "Quanzhou",
    "đài bắc": "Taipei",
    "phiên âm bạch thoại-like": "POJ",
    "phonetic": "Phonetic",
    "ipa": "IPA",
    "ngô": "Wu",
    "northern": "Northern",
    "shanghai": "Shanghai",
}

ZH_DIAL_TAGS = {
    "chính thức": "formal",
    "bạch thoại": "Written-vernacular-Chinese",
    "quan thoại giao-liêu": "Jiaoliao-Mandarin",
    "yên đài": "Yantai",
    "mưu bình": "Muping",
    "quan thoại trung nguyên": "Central-Plains-Mandarin",
    "lạc dươn": "Luoyang",
    "vạn vinh": "Wanrong",
    "tây ninh": "Xining",
    "quan thoại lan-ngân": "Lanyin-Mandarin",
    "ngân xuyên": "Yinchuan",
    "quan thoại tây nam": "Southwestern-Mandarin",
    "liễu châu": "Liuzhou",
    "quan thoại giang hoài": "Jianghuai-Mandarin",
    "nam kinh": "Nanjing",
    "dương châu": "Yangzhou",
    "quảng châu": "Guangzhou",
    "đông hoản": "Dongguan",
    "huy châu": "Huizhou",
    "tích khê": "Jixi",
    "tấn": "Jin",
    "thái nguyên": "Taiyuan",
    "đài nam": "Tainan",
    "lôi châu": "Leizhou",
    "mân phủ tiên": "Puxian-Min",
    "bình nam": "Southern-Pinghua",
    "nam ninh": "Nanning",
    "đình tử": "Tingzi",
    "thượng hải": "Shanghai",
    "tô châu": "Suzhou",
    "đan dương": "Danyang",
    "hàng châu": "Hangzhou",
    "ninh ba": "Ningbo",
    "ôn châu": "Wenzhou",
    "kim hoa": "Jinhua",
    "tương": "Xiang",
    "trường sa": "Changsha",
    "quan thoại đông bắc": "Northeastern-Mandarin",
    "quan thoại ký-lỗ": "Jilu-Mandarin",
    "cám": "Cantonese",
    "mân trung sơn": "Zhongshan-Min",
    "trung sơn": "Zhongshan",
    "long đô": "Longdu",
    "sa khê": "Shaxi",
}

TH_PRON_TAGS = {
    "chính tả": "orthographic",
    "âm vị": "phonemic",
    "chính tả/âm vị": ["orthographic", "phonemic"],
    "chuyển tự": "romanization",
    "paiboon": "Paiboon",
    "viện hoàng gia": "Royal-Institute",
}


TAGS = {
    **LABEL_TAGS,
    **GENDER_NUMBER_TAGS,
    **LOCATIONS,
    **SOUND_TAGS,
    **ZH_X_TAGS,
    **ZH_PRON_TAGS,
    **ZH_DIAL_TAGS,
    **TH_PRON_TAGS,
}

# https://vi.wiktionary.org/wiki/Mô_đun:labels/data/topical
TOPICS = {
    "địa chấn học": "seismology",
    "thực vật học": "botany",
    "hóa học": "chemistry",
    "từ lóng người đồng tính": "LGBT",
    "từ lóng quân sự": "military",
    "bóng chày": "baseball",
    "bóng rổ": "basketball",
    "băng cầu": "ice-hockey",
    "bắn cung": "archery",
    "chính trị": "politics",
    "cơ khí": "mechanical",
    "cử tạ": "weightlifting",
    "dược học": "pharmaceuticals",
    "giải phẫu học": "anatomy",
    "hàng hải": "shipping",
    "hàng không": "aviation",
    "in ấn": "printing",
    "khoa đo lường": "metrology",
    "khoáng vật học": "mineralogy",
    "khúc côn cầu": "hockey",
    "khảo cổ học": "archeology",
    "kinh doanh": "business",
    "kinh tế học": "economics",
    "kiến trúc": "architecture",
    "kiểu cách": "manner",
    "kế toán": "accounting",
    "kỹ thuật": "technology",
    "luật pháp": "law",
    "lâm nghiệp": "forestry",
    "lôgic": "logic",
    "lập trình": "programming",
    "nghệ thuật": "arts",
    "ngoại giao": "diplomacy",
    "ngành mỏ": "mining",
    "nhân khẩu học": "demographics",
    "nhãn khoa": "ophthalmology",
    "nấu nướng": "cooking",
    "sinh thái học": "ecology",
    "sinh vật học": "biology",
    "sân khấu": "theater",
    "săn bắn": "hunting",
    "thương nghiệp": "commerce",
    "thần học": "theology",
    "thần thoại": "mythology",
    "thể dục": "exercise",
    "thể thao": "sports",
    "tin học": "computer-sciences",
    "tài chính": "finance",
    "tôn giáo": "religion",
    "văn học": "literature",
    "vật lý học": "physics",
    "xã hội học": "sociology",
    "y học": "medicine",
    "đạo giáo": "Taoism",
    "điện học": "electricity",
    "điện tử học": "electronics",
    "điện ảnh": "film",
    "đánh bài": "gambling",
    "đường sắt": "railways",
    "đại số": "algebra",
    "động vật học": "zoology",
    "nông nghiệp": "agriculture",
    "phi cơ": "airplane",
    "đại số học": "algebra",
    "bóng đá mỹ": "American-football",
    "lưỡng cư": "amphibian",
    "bài tập": "exercise",
    "đấu kiếm": "fencing",
    "âm học": "acoustics",
    "diễn xuất": "acting",
    "quảng cáo": "advertising",
    "hàng không học": "aeronautics",
    "hàng không vũ trụ": "aerospace",
    "tình cảm": "affection",
    "khí cụ bay": "aircraft",
    "giả kim thuật": "alchemy",
    "thức uống có cồn": ["alcohol", "beverages"],
    "lạm dụng rượu bia": "alcoholism",
    "hình học đại số": "algebraic-geometry",
    "tô pô đại số": "algebraic-topology",
    "y học thay thế": "alternative-medicine",
    "phát thanh nghiệp dư": "radio",
    "bóng bầu dục Mỹ": ["US", "football"],
    "hình học giải tích": "geometry",
    "hóa phân tích": "chemistry",
    "chủ nghĩa vô trị": "anarchism",
    "anh giáo": "Anglicanism",
    "nhân loại học": "anthropology",
    "toán học ứng dụng": "applied-mathematics",
    "số học": "arithmetic",
    "trí tuệ nhân tạo": "artificial-intelligence",
    "chiêm tinh học": "astrology",
    "thiên văn học": "astronomy",
    "vật lý thiên văn": "astrophysics",
    "điền kinh": "athletics",
    "ô tô": "automotive",
    "trò chơi với bóng": "ball-games",
    "ngân hàng": "banking",
    "bdsm": "BDSM",
    "kinh thánh": "biblical",
    "hóa sinh": "biochemistry",
    "sinh học": "biology",
    "trò chơi với bàn cờ": "board-games",
    "quyền anh": "boxing",
    "phát sóng": "broadcasting",
    "rêu học": "bryology",
    "phật giáo": "Buddhism",
    "vi tích phân": "calculus",
    "họ lạc đà": "camelids",
    "trò chơi bài": "card-games",
    "bệnh học tim": "cardiology",
    "công giáo": "Catholicism",
    "kỹ thuật hóa học": "chemical-engineering",
    "cờ vua": "chess",
    "thần thoại trung hoa": "Chinese-philosophy",
    "kitô giáo": "Christianity",
    "trang phục": "clothing",
    "truyện tranh": "comics",
    "giao tiếp": "communications",
    "chủ nghĩa cộng sản": "communism",
    "giải tích phức": "complex-analysis",
    "đồ hoạ máy tính": "computer-graphics",
    "phần cứng": "computer-hardware",
    "khoa học máy tính": "computer-sciences",
    "bảo mật máy tính": "computer-security",
    "máy tính": "computing",
    "nho giáo": "Confucianism",
    "nấu ăn": "cooking",
    "phân thứ bộ cua": "crabs",
    "tội phạm": "crime",
    "phân ngành giáp xác": "Crustaceans",
    "điều khiển học": "cybernetics",
    "đạp xe": "cycling",
    "sinh học tế bào": "cytology",
    "chế phẩm sữa": "dairy-products",
    "nha khoa": "dentistry",
    "món tráng miệng": "desserts",
    "chó": "dogs",
    "giáo dục": "education",
    "thần thoại ai cập": "Egyptian-mythology",
    "ai cập học": "Egyptology",
    "kỹ thuật điện": "electrical-engineering",
    "điện": "electricity",
    "điện từ học": "electromagnetism",
    "kĩ thuật": "engineering",
    "tri thức luận": "epistemology",
    "văn học khiêu dâm": "erotic-literature",
    "thuyết tiến hoá": "evolutionary-theory",
    "kì ảo": "fantasy",
    "hư cấu": "fiction",
    "phim": "film",
    "súng cầm tay": "firearms",
    "hoa": "flowery",
    "cơ học chất lưu": "fluid-dynamics",
    "văn hóa dân gian": "folklore",
    "hàm toán học": "functions",
    "giải tích hàm": "functional-analysis",
    "đồ nội thất": "furniture",
    "trò chơi": "games",
    "di truyền học": "genetics",
    "địa lí học": "geography",
    "địa chất học": "geology",
    "hình học": "geometry",
    "địa mạo học": "geomorphology",
    "chính phủ": "government",
    "ngữ pháp": "grammar",
    "giao diện đồ họa người dùng": "graphical-user-interface",
    "thần thoại hy lạp": "Greek-mythology",
    "thể dục dụng cụ": "gymnastics",
    "huyết học": "hematology",
    "ấn độ giáo": "Hinduism",
    "lịch sử thời đại": "history",
    "lịch sử": "history",
    "vi lượng đồng căn": "homeopathy",
    "họ người": "hominids",
    "làm vườn": "horticulture",
    "săn": "hunting",
    "thủy văn học": "hydrology",
    "khúc côn cầu trên băng": "ice-hockey",
    "ngư học": "ichthyology",
    "ý thức hệ": "ideology",
    "miễn dịch học": "immunology",
    "luật quốc tế": "law",
    "quan hệ quốc tế": "international-relations",
    "hồi giáo": "Islam",
    "kỳ na giáo": "Jainism",
    "tác phẩm giả tưởng nhật bản": "Japanese-fiction",
    "do thái giáo": "Judaism",
    "luật pháp hoa kỳ": "law",
    "luật pháp việt nam": "law",
    "từ điển học": "lexicography",
    "lgbt": "LGBT",
    "nguồn ánh sáng": "light-sources",
    "đại số tuyến tính": "linear-algebra",
    "ngôn ngữ học": "linguistics",
    "sản xuất": "manufacturing",
    "chủ nghĩa marx": "Marxism",
    "giải tích toán học": "mathematical-analysis",
    "toán học": "mathematics",
    "cơ học": "mechanics",
    "thần thoại lưỡng hà": "Mesopotamian-mythology",
    "luyện kim": "metallurgy",
    "siêu hình học": "metaphysics",
    "khí tượng học": "meteorology",
    "đo lường học": "metrology",
    "vi sinh vật học": "microbiology",
    "quân sự": "military",
    "tiền": "money",
    "đua xe có động cơ": "motor-racing",
    "âm nhạc": "music",
    "nấm học": "mycology",
    "giải phẫu thần kinh": "neuroanatomy",
    "thần kinh học": "neurology",
    "khoa học thần kinh": "neuroscience",
    "họ cà": "nightshades",
    "hóa tệ học": "numismatics",
    "thần bí học": "occult",
    "hải dương học": "oceanography",
    "hệ điều hành": "operating-systems",
    "quang học": "optics",
    "họ lan": "Orchids",
    "hóa hữu cơ": "organic-chemistry",
    "điểu học": "ornithology",
    "chính tả": "orthography",
    "pagan giáo": "paganism",
    "cổ sinh vật học": "paleontology",
    "bệnh lí học": "pathology",
    "thổ nhưỡng học": "pedology",
    "hóa dầu": "petrochemistry",
    "thạch luận": "petrology",
    "dược lý học": "pharmacology",
    "triết học": "philosophy",
    "ngữ âm": "phonetics",
    "âm vị học": "phonology",
    "nhiếp ảnh": "photography",
    "não tướng học": "physiognomy",
    "sinh lí học": "physiology",
    "bộ hồ tiêu": "piperales",
    "khoa học hành tinh": "planetology",
    "thơ": "poetry",
    "khoa học chính trị": "political-science",
    "chính trị úc": "politics",
    "chính trị philippines": "politics",
    "khiêu dâm": "pornography",
    "tâm thần học": "psychiatry",
    "tâm lý học": "psychology",
    "vận tải đường sắt": "rail-transport",
    "tài liệu tham khảo": "reference-works",
    "giáo hội công giáo": "Roman-Catholicism",
    "thần thoại la mã": "Roman-mythology",
    "xoay tròn": "rotation",
    "khoa học viễn tưởng": "science-fiction",
    "khoa học": "sciences",
    "chứng khoán": "securities",
    "ngữ nghĩa học": "semantics",
    "lí thuyết tập hợp": "set-theory",
    "tình dục": "sex",
    "tình dục học": "sexology",
    "tính dục": "sexuality",
    "ca hát": "singing",
    "bóng đá": "soccer",
    "khoa học xã hội": "social-sciences",
    "chủ nghĩa xã hội": "socialism",
    "phương tiện truyền thông mạng xã hội": "social-media",
    "ngôn ngữ học xã hội": "sociolinguistics",
    "phổ học": "spectroscopy",
    "bơi lội": "swimming",
    "hệ thống": "systems",
    "lý thuyết hệ thống": "systems-theory",
    "phân loại học": "taxonomy",
    "công nghệ": "technology",
    "quái thai học": "teratology",
    "dệt may": "textiles",
    "nhiệt động học": "thermodynamics",
    "du lịch": "tourism",
    "đông y": "traditional-Chinese-medicine",
    "người chuyển giới": "transgender",
    "giao thông": "transport",
    "lượng giác": "trigonometry",
    "hàm lượng giác": "trigonometric-function",
    "đơn vị đo": "units-of-measure",
    "rau": "vegetable",
    "phương tiện giao thông": "vehicles",
    "thú y": "veterinary-medicine",
    "nén video": "video-compression",
    "núi lửa học": "volcanology",
    "thời tiết": "weather",
    "môn thể thao mùa đông": "winter-sports",
    "nhân vật kinh thánh": "biblical",
    "chòm sao": "constellation",
    "bệnh": "disease",
    "acid béo": "fatty-acid",
    "tu từ học": "figure-of-speech",
    "vị thần hy lạp": "Greek-god",
    "huy hiệu học": "heraldic-charge",
    "thần thánh ấn độ": "Hindu-god",
    "hợp chất vô cơ": "inorganic-compound",
    "địa mạo": "landforms",
    "khoáng vật": "mineralogy",
    "điện thoại di động": "mobile-phones",
    "nhạc cụ": "musical-instruments",
    "hóa học hữu cơ": "organic-compound",
    "thực vật": "plant",
    "bộ xương": "skeleton",
    "tàu chiến": "warships",
    "nước": "water",
}


def translate_raw_tags(data: WordEntry) -> None:
    raw_tags = []
    for raw_tag in data.raw_tags:
        found_tag = False
        if raw_tag.lower() in TAGS and hasattr(data, "tags"):
            found_tag = True
            tr_tag = TAGS[raw_tag.lower()]
            if isinstance(tr_tag, str):
                data.tags.append(tr_tag)
            elif isinstance(tr_tag, list):
                data.tags.extend(tr_tag)
        if raw_tag.lower() in TOPICS and hasattr(data, "topics"):
            found_tag = True
            topic = TOPICS[raw_tag.lower()]
            if isinstance(topic, str):
                data.topics.append(topic)
            elif isinstance(topic, list):
                data.topics.extend(topic)
        if not found_tag:
            raw_tags.append(raw_tag)
    data.raw_tags = raw_tags
