# pos templates
# https://nl.wiktionary.org/wiki/Categorie:Woordsoortsjablonen
POS_DATA = {
    "Afkorting": {"pos": "abbrev", "tags": ["abbreviation"]},
    "Bijvoeglijk naamwoord": {"pos": "adj"},
    "Bijwoord": {"pos": "adv"},
    "Telbijwoord": {"pos": "adv", "tags": ["numeral"]},
    "Lidwoord": {"pos": "article"},
    "Cijfer": {"pos": "num", "tags": ["number"]},
    "Omvoegsel": {"pos": "circumfix", "tags": ["morpheme"]},
    "Voegwoord": {"pos": "conj"},
    "Contractie": {"pos": "contraction", "tags": ["contraction"]},
    "Ideofoon": {"pos": "noun", "tags": ["ideophone"]},
    "Invoegsel": {"pos": "interfix", "tags": ["morpheme"]},
    "Tussenwerpsel": {"pos": "intj"},
    "Leesteken": {"pos": "punct", "tags": ["punctuation"]},
    "Letter": {"pos": "character", "tags": ["letter"]},
    "Eigennaam": {"pos": "name"},
    "Zelfstandig naamwoord": {"pos": "noun"},
    "Hoofdtelwoord": {"pos": "num"},
    "Verdelingsgetal": {"pos": "num", "tags": ["distributive"]},
    "Onbepaald hoofdtelwoord": {"pos": "num", "tags": ["indefinite"]},
    "Vragend telwoord": {"pos": "num", "tags": ["interrogative"]},
    "Soorttelwoord": {"pos": "num"},
    "Rangtelwoord": {"pos": "adj", "tags": ["ordinal"]},
    "Onbepaald rangtelwoord": {"pos": "adj", "tags": ["ordinal", "indefinite"]},
    "Deelwoord": {"pos": "verb", "tags": ["participle"]},
    "Frase": {"pos": "phrase"},
    "Achterzetsel": {"pos": "postp"},
    "Voorvoegsel": {"pos": "prefix", "tags": ["morpheme"]},
    "Voorzetsel": {"pos": "prep"},
    "Voorzetselvorm": {"pos": "prep", "tags": ["form-of"]},
    "Voornaamwoordelijk bijwoord": {"pos": "adv", "tags": ["pronominal"]},
    "Aanwijzend voornaamwoord": {"pos": "pron", "tags": ["demonstrative"]},
    "Uitroepend voornaamwoord": {"pos": "pron"},
    "Onbepaald voornaamwoord": {"pos": "pron", "tags": ["indefinite"]},
    "Vragend voornaamwoord": {"pos": "pron", "tags": ["interrogative"]},
    "Persoonlijk voornaamwoord": {"pos": "pron", "tags": ["person"]},
    "Bezittelijk voornaamwoord": {"pos": "pron", "tags": ["possessive"]},
    "Wederkerig voornaamwoord": {"pos": "pron", "tags": ["reciprocal"]},
    "Wederkerend voornaamwoord": {"pos": "pron", "tags": ["reflexive"]},
    "Betrekkelijk voornaamwoord": {"pos": "pron", "tags": ["relative"]},
    "Temporeel voornaamwoord": {"pos": "pron", "tags": ["temporal"]},
    "Voornaamwoord": {"pos": "pron"},
    "Partikel": {"pos": "particle"},
    "Achtervoegsel": {"pos": "suffix", "tags": ["morpheme"]},
    "Symbool": {"pos": "symbol"},
    "Werkwoord": {"pos": "verb"},
}


LINKAGE_SECTIONS = {
    "Anagrammen": "anagrams",
    "Antoniemen": "antonyms",
    "Afgeleide begrippen": "derived",
    "Uitdrukkingen en gezegden": "proverbs",
    "Holoniemen": "holonyms",
    "Gelijkklinkende woorden": "homophones",
    "Hyperoniemen": "hypernyms",
    "Hyponiemen": "hyponyms",
    "Hyponiemen (in taxonomische zin)": "hyponyms",
    "Meroniemen": "metonyms",
    "Paroniemen": "paronyms",
    "Spreekwoorden": "proverbs",
    "Verwante begrippen": "related",
    "Rijmwoorden": "rhymes",
    "Synoniemen": "synonyms",
    "Typische woordcombinaties": "derived",
}
