# List of templates
# https://ja.wiktionary.org/wiki/Wiktionary:テンプレートの一覧#品詞表記
POS_DATA = {
    "名詞": {"pos": "noun"},
    "数詞": {"pos": "num"},
    "固有名詞": {"pos": "name"},
    "代名詞": {"pos": "pron"},
    "動詞": {"pos": "verb"},
    "自動詞": {"pos": "verb", "tags": ["intransitive"]},
    "他動詞": {"pos": "verb", "tags": ["transitive"]},
    "助動詞": {"pos": "verb", "tags": ["auxiliary"]},
    "副詞": {"pos": "adv"},
    "形容詞": {"pos": "adj"},
    "形容動詞": {"pos": "adj_noun"},
    "助詞": {"pos": "particle"},
    "冠詞": {"pos": "article"},
    "前置詞": {"pos": "prep"},
    "後置詞": {"pos": "postp"},
    "間投詞": {"pos": "intj"},
    "分詞": {"pos": "verb", "tags": ["participle"]},
    "過去分詞": {"pos": "verb", "tags": ["participle", "past"]},
    "現在分詞": {"pos": "verb", "tags": ["participle", "present"]},
    "接続詞": {"pos": "conj"},
    "類別詞": {"pos": "classifier"},
    "接頭辞": {"pos": "prefix", "tags": ["morpheme"]},
    "接頭語": {"pos": "prefix", "tags": ["morpheme"]},
    "接尾辞": {"pos": "suffix", "tags": ["morpheme"]},
    "接尾語": {"pos": "suffix", "tags": ["morpheme"]},
    "語尾": {"pos": "suffix", "tags": ["morpheme"]},
    "接辞": {"pos": "affix"},
    # "小詞"
    # "修飾詞"
    # "疑問詞"
    "和語の漢字表記": {"pos": "unknown", "tags": ["kanji", "form-of"]},
    "成句": {"pos": "phrase", "tags": ["idiomatic"]},
    "成語": {"pos": "phrase", "tags": ["idiomatic"]},
    "縮約形": {"pos": "contraction"},
    "略語": {"pos": "abbrev", "tags": ["abbreviation"]},
    "頭字語": {"pos": "abbrev", "tags": ["abbreviation"]},
    "ことわざ": {"pos": "proverb"},
    "感動詞": {"pos": "intj"},
    "人名": {"pos": "name"},
    "意義": {"pos": "unknown"},
    "不変化詞": {"pos": "particle"},
    "人称代名詞": {"pos": "pron", "tags": ["person"]},
    "介詞": {"pos": "prep"},
    "ラテン文字表記": {"pos": "romanization"},
    "位置名詞": {"pos": "noun"},
    "不定冠詞": {"pos": "article", "tags": ["indefinite"]},
    "不定代名詞": {"pos": "pron", "tags": ["indefinite"]},
    "キリル文字": {"pos": "character", "tags": ["Cyrillic", "letter"]},
    "アラビア文字": {"pos": "character", "tags": ["Arabic", "letter"]},
    "オノマトペ": {"pos": "noun", "tags": ["onomatopoeic"]},
    "擬声語": {"pos": "noun", "tags": ["onomatopoeic"]},
    "依存名詞": {"pos": "noun"},
    "修飾詞": {"pos": "adj"},
    "冠形詞": {"pos": "det"},
    "助数詞": {"pos": "counter"},
    "助詞（不変化詞）": {"pos": "particle"},
    "個数詞": {"pos": "num"},
    "動詞句": {"pos": "phrase", "tags": ["verb"]},
    "間投詞句": {"pos": "phrase", "tags": ["interjection"]},
    "単位記号": {"pos": "symbol"},
    "句動詞": {"pos": "phrase", "tags": ["verb"]},
    "慣用句": {"pos": "phrase", "tags": ["idiomatic"]},
    "名詞句": {"pos": "phrase", "tags": ["noun"]},
    "定冠詞": {"pos": "article", "tags": ["definite"]},
    "字義": {"pos": "character"},
    "数学記号": {"pos": "symbol"},
    "所有代名詞": {"pos": "det", "tags": ["possessive"]},
    "拡張子": {"pos": "symbol"},
    "数字": {"pos": "num", "tags": ["number"]},
    "接続助詞": {"pos": "particle", "tags": ["conjunctive"]},
    "指示代名詞": {"pos": "pron", "tags": ["demonstrative"]},
    "接合辞": {"pos": "interfix", "tags": ["morpheme"]},
    "指示形容詞": {"pos": "adj", "tags": ["demonstrative"]},
    "所有形容詞": {"pos": "adj", "tags": ["possessive"]},
    "方位詞": {"pos": "noun"},
    "略号": {"pos": "symbol"},
    "疑問詞": {"pos": "pron", "tags": ["interrogative"]},
    "疑問代名詞": {"pos": "pron", "tags": ["interrogative"]},
    "疑問副詞": {"pos": "adv", "tags": ["interrogative"]},
    "記号": {"pos": "symbol"},
    "英数字混合表記": {"pos": "noun"},
    "線文字A": {"pos": "symbol"},
    "量詞": {"pos": "classifier"},
    "造語成分": {"pos": "noun"},
    "連体詞": {"pos": "adnominal"},
    "速記記号": {"pos": "symbol"},
    "錬金術記号": {"pos": "symbol"},
    "限定詞": {"pos": "det"},
}

LINKAGES = {
    "類義語": "synonyms",
    "同義句": "synonyms",
    "同義語": "synonyms",
    "対義語": "antonyms",
    "対義句": "antonyms",
    "上位語": "hypernyms",
    "下位語": "hyponyms",
    "全体語": "holonyms",
    "部分語": "meronyms",
    "複合語": "derived",
    "派生語": "derived",
    "縮約形": "contraction",
    "略語": "abbreviations",
    "省略形": "abbreviations",
    "関連語": "related",
    "同族語": "coordinate_terms",
    "熟語": "proverbs",
    "成句": "phrases",
    "成語": "phrases",
    "連語": "collocations",
    "同系語": "cognates",
    "諸言語への影響": "descendants",
    "アナグラム": "anagrams",
    "ことわざ": "proverbs",
    "他の関連語": "related",
}
