# https://id.wiktionary.org/wiki/Kategori:Templat_kelas_kata
# https://id.wiktionary.org/wiki/Kategori:Templat_umum
POS_DATA = {
    "Adjektiva": {"pos": "adj"},
    "Adverbia": {"pos": "adv"},
    "Akronim": {"pos": "abbrev", "tags": ["abbreviation"]},
    "Artikula": {"pos": "article"},
    "Kelas kata belum ditentukan": {"pos": "unknown"},
    "Penggolong": {"pos": "classifier"},
    "Interjeksi": {"pos": "intj"},
    "Interogativa": {"pos": "pron", "tags": ["interrogative"]},
    "Konjungsi": {"pos": "conj"},
    "Nomina": {"pos": "noun"},
    "Numeralia": {"pos": "num"},
    "Partikel": {"pos": "particle"},
    "Preposisi": {"pos": "prep"},
    "Pronomina": {"pos": "pron"},
    "Subjungsi": {"pos": "conj"},
    "Verba": {"pos": "verb"},
    "Akar kata": {"pos": "root", "tags": ["morpheme"]},
    "Akhiran": {"pos": "suffix", "tags": ["morpheme"]},
    "Huruf": {"pos": "character", "tags": ["letter"]},
    "Inisialisme": {"pos": "abbrev", "tags": ["abbreviation"]},
    "Awalan": {"pos": "prefix", "tags": ["morpheme"]},
    "Kontraksi": {"pos": "contraction", "tags": ["contraction"]},
    "Singkatan": {"pos": "abbrev", "tags": ["abbreviation"]},
    "Nama diri": {"pos": "name"},
    "Arti": {"pos": "unknown"},
    "Hanzi": {"pos": "character", "tags": ["hanzi"]},
    "Kanji": {"pos": "character", "tags": ["kanji"]},
    "Hanja": {"pos": "character", "tags": ["Hanja"]},
    "Idiom": {"pos": "phrase", "tags": ["idiomatic"]},
    "Karakter Han": {"pos": "character", "tags": ["han"]},
    "Kata benda": {"pos": "noun"},
    "Kata kerja": {"pos": "verb"},
    "Simbol": {"pos": "symbol"},
}


LINKAGE_SECTIONS = {
    "Sinonim": "synonyms",
    "Antonim": "antonyms",
    "Kata turunan": "derived",
    "Frasa dan kata majemuk": "derived",
    "Lihat pula": "related",
    "Kata terkait": "related",
    "Akar kata": "related",
    "Turunan": "derived",
    "Peribahasa": "proverbs",
    "Variasi": "forms",
    "Alternatif": "alt_forms",
    "Frasa turunan": "derived",
    "Bentuk alternatif": "alt_forms",
    "Lihat juga": "related",
    "Kata majemuk": "derived",
    "Ungkapan": "related",
}
