# https://fr.wiktionary.org/wiki/Annexe:Glossaire_grammatical

TOPIC_TAGS: dict[str, str] = {
    "géographie": "geography",
    "agriculture": "agriculture",
    "botanique": "botany",
    "zoologie": "zoology",
    "anatomie": "anatomy",
    "médecine": "medicine",
    "chimie": "chemistry",
    "linguistique": "linguistics",
    "ornithologie": "ornithology",
    "musique": "music",
    "religion": "religion",
    "cuisine": "cuisine",
    "informatique": "computing",
    "biochimie": "biochemistry",
    "charpenterie": "carpentry",
    "menuiserie": "carpentry",
    "littérature": "literature",
    "marine": "nautical",
    "histoire": "history",
    "astrologie": "astrology",
    "droit": "law",
    "politique": "politics",
    "militaire": "military",
    "physique": "physics",
    "programmation": "programming",
    "mathématiques": "mathematics",
    "biologie": "biology",
    "astronomie": "astronomy",
    "sport": "sports",
    "finance": "finance",
    "minéralogie": "mineralogy",
    "grammaire": "linguistics",
    "journalisme": "journalism",
    "commerce": "commerce",
    "habillement": "textiles fashion",
}
