# https://zh.wiktionary.org/wiki/Template:Label
LABEL_TOPICS: dict[str, str] = {
    "天文學": "astronomy",
    "医": "medicine",
    "宗": "religion",
    "语": "linguistics",
    "生": "biochemistry",
    "计算机": "computing",
    "計算機": "computing",
    "航空学": "aeronautics",
    "法律": "law",
    "电": "electricity",
    "银行业": "business",
    "执法": "government",
    "英国": "UK",
    "角色扮演游戏": "games",
    "运输": "transport",
    "網路": "internet",
    "軍事": "military",
    "科學": "sciences",
    "教育": "education",
    "化學": "chemistry",
    "電信": "telecommunications",
}
