from ...config import POSSubtitleData

# some are template names
POS_TITLES: dict[str, POSSubtitleData] = {
    "abreviatura": {"pos": "abbrev"},
    "acrónimo": {"pos": "abbrev"},
    "adjetivo cardinal": {"pos": "num", "tags": ["cardinal"]},
    "adjetivo demostrativo": {"pos": "adj", "tags": ["demonstrative"]},
    "adjetivo indefinido": {"pos": "adj", "tags": ["indefinite"]},
    "adjetivo indeterminado": {"pos": "adj", "tags": ["indeterminate"]},
    "adjetivo interrogativo": {"pos": "adj", "tags": ["interrogative"]},
    "adjetivo numeral": {"pos": "num", "tags": ["numeral"]},
    "adjetivo ordinal": {"pos": "num", "tags": ["ordinal"]},
    "adjetivo posesivo": {"pos": "adj", "tags": ["possessive"]},
    "adjetivo relativo": {"pos": "adj", "tags": ["relative"]},
    "adjetivo": {"pos": "adj"},
    "adjetivos": {"pos": "adj"},
    "adverbio comparativo": {"pos": "adv", "tags": ["comparative"]},
    "adverbio de afirmación": {"pos": "adv", "tags": ["affirmative"]},
    "adverbio de cantidad": {"pos": "adv", "tags": ["quantitative"]},
    "adverbio de duda": {"pos": "adv"},
    "adverbio de lugar": {"pos": "adv", "tags": ["place"]},
    "adverbio de modo": {"pos": "adv", "tags": ["mood"]},
    "adverbio de negación": {"pos": "adv", "tags": ["negative"]},
    "adverbio de orden": {"pos": "adv", "tags": ["order"]},
    "adverbio de tiempo": {"pos": "adv"},
    "adverbio demostrativo": {"pos": "adv", "tags": ["demonstrative"]},
    "adverbio interrogativo": {"pos": "adv", "tags": ["interrogative"]},
    "adverbio relativo": {"pos": "adv", "tags": ["relative"]},
    "adverbio": {"pos": "adv"},
    "adverbios": {"pos": "adv"},
    "afijo": {"pos": "affix"},
    "antropónimo": {"pos": "name"},
    "artículo determinado": {"pos": "article", "tags": ["determinate"]},
    "artículo indeterminado": {"pos": "article", "tags": ["indeterminate"]},
    "artículo": {"pos": "article"},
    "caracteres han": {"pos": "character"},
    "circunfijo": {"pos": "circumfix"},
    "conjunción adversativa": {"pos": "conj", "tags": ["adversative"]},
    "conjunción ilativa": {"pos": "conj", "tags": ["illative"]},
    "conjunción": {"pos": "conj"},
    "contracción": {"pos": "contraction", "tags": ["contraction"]},
    "dígrafo": {"pos": "character"},
    "expresión": {"pos": "phrase"},
    "forma adjetiva": {"pos": "adj", "tags": ["form-of"]},
    "forma de participio": {"pos": "participle", "tags": ["form-of"]},
    "forma de sufijo": {"pos": "suffix", "tags": ["form-of"]},
    "forma flexiva": {"pos": "verb", "tags": ["form-of"]},
    "forma pronominal": {"pos": "pron", "tags": ["form-of"]},
    "forma sustantiva femenina": {
        "pos": "noun",
        "tags": ["form-of", "feminine"],
    },
    "forma sustantiva masculina": {
        "pos": "noun",
        "tags": ["form-of", "masculine"],
    },
    "forma sustantiva neutra": {"pos": "noun", "tags": ["form-of", "neuter"]},
    "forma sustantiva": {"pos": "noun", "tags": ["form-of"]},
    "forma sustantiva plural": {"pos": "noun", "tags": ["form-of", "plural"]},
    "forma verbal": {"pos": "verb", "tags": ["form-of"]},
    "infijo": {"pos": "infix", "tags": ["morpheme"]},
    "interjección": {"pos": "intj"},
    "letra": {"pos": "character"},
    "locución adjetiva": {"pos": "phrase", "tags": ["adjective"]},
    "locución adverbial": {"pos": "phrase", "tags": ["adverbial"]},
    "locución conjuntiva": {"pos": "phrase", "tags": ["conjunctive"]},
    "locución interjectiva": {"pos": "phrase", "tags": ["interjection"]},
    "locución prepositiva": {"pos": "phrase", "tags": ["prepositional"]},
    "locución pronominal": {"pos": "phrase", "tags": ["pronominal"]},
    "locución sustantiva": {"pos": "phrase"},
    "locución verbal": {"pos": "phrase"},
    "locución": {"pos": "phrase"},
    "nombre propios": {"pos": "name"},
    "onomatopeya": {"pos": "noun"},
    "partícula": {"pos": "particle"},
    "postposición": {"pos": "postp"},
    "prefijo": {"pos": "prefix"},
    "preposición de ablativo": {"pos": "prep", "tags": ["ablative"]},
    "preposición de acusativo o ablativo": {
        "pos": "prep",
        "tags": ["accusative", "ablative"],
    },
    "preposición de acusativo": {"pos": "prep", "tags": ["accusative"]},
    "preposición de genitivo": {"pos": "prep", "tags": ["genitive"]},
    "preposición": {"pos": "prep"},
    "pronombre demostrativo": {"pos": "pron", "tags": ["demonstrative"]},
    "pronombre indefinido": {"pos": "pron", "tags": ["indefinite"]},
    "pronombre interrogativo": {"pos": "pron", "tags": ["interrogative"]},
    "pronombre personal": {"pos": "pron", "tags": ["personal"]},
    "pronombre posesivo": {"pos": "pron", "tags": ["possessive"]},
    "pronombre relativo": {"pos": "pron", "tags": ["relative"]},
    "pronombre": {"pos": "pron"},
    "refrán": {"pos": "proverb"},
    "sigla": {"pos": "abbrev"},
    "símbolo": {"pos": "symbol"},
    "sufijo flexivo": {"pos": "suffix"},
    "sufijo": {"pos": "suffix"},
    "sustantivo ambiguo": {"pos": "noun", "tags": ["masculine", "feminine"]},
    "sustantivo animado": {"pos": "noun", "tags": ["animate"]},
    "sustantivo común": {"pos": "noun"},
    "sustantivo femenino y masculino": {
        "pos": "noun",
        "tags": ["masculine", "feminine"],
    },
    "sustantivo femenino": {"pos": "noun", "tags": ["feminine"]},
    "sustantivo inanimado": {"pos": "noun", "tags": ["inanimate"]},
    "sustantivo masculino": {"pos": "noun", "tags": ["masculine"]},
    "sustantivo neutro y masculino": {
        "pos": "noun",
        "tags": ["neuter", "masculine"],
    },
    "sustantivo neutro": {"pos": "noun", "tags": ["neuter"]},
    "sustantivo propio": {"pos": "name"},
    "sustantivo propio/pruebas": {"pos": "name"},
    "sustantivo": {"pos": "noun"},
    "verbo auxiliar": {"pos": "verb", "tags": ["auxiliary"]},
    "verbo impersonal": {"pos": "verb", "tags": ["impersonal"]},
    "verbo intransitivo": {"pos": "verb", "tags": ["intransitive"]},
    "verbo modal": {"pos": "verb", "tags": ["modal"]},
    "verbo perfectivo": {"pos": "verb", "tags": ["perfective"]},
    "verbo pronominal": {"pos": "verb", "tags": ["pronominal"]},
    "verbo transitivo": {"pos": "verb", "tags": ["transitive"]},
    "verbo": {"pos": "verb"},
}

LINKAGE_TITLES: dict[str, str] = {
    "antónimo": "antonyms",
    "compuestos": "compounds",
    "derivad": "derived",
    "hipónimo": "hyponyms",
    "hiperónimo": "hypernyms",
    "merónimo": "meronyms",
    "locucion": "idioms",
    "locuciones": "idioms",
    "relacionado": "related",
    "refranes": "proverbs",
    "sinónimo": "synonyms",
}

IGNORED_TITLES: frozenset[str] = frozenset(["véase también"])

TRANSLATIONS_TITLES: frozenset[str] = frozenset(["traducciones", "traducción"])
