from .models import WordEntry

# https://es.wiktionary.org/wiki/Wikcionario:Lista_de_etiquetas

# https://es.wiktionary.org/wiki/Plantilla:csem
CSEM_TOPICS = {
    "aeronáutica": "aeronautics",
    "agricultura": "agriculture",
    "ajedrez": "chess",
    #  "Algas": "algae",
    "alimento": "food",
    "alimentos": "food",
    "alpinismo": "mountaineering",
    "alquimia": "alchemy",
    "anatomía": "anatomy",
    #  "Anfibios": "amphibians",
    #  "Angiología": "angiology",
    #  "Animales": "animals",
    #  "Animales extintos": "extinct animals",
    "antropología": "anthropology",
    #  "Antropotomía": "anthropotomy",
    #  "Antropónimos": "anthroponyms",
    #  "Anélidos": "annelids",
    #  "Apellidos": "surnames",
    "apicultura": "beekeeping",
    #  "Arbustos": "shrubbery",
    "aritmética": "arithmetic",
    "armas": "weaponry",
    "arqueología": "archeology",
    "arquitectura": "architecture",
    "arte": "art",
    "arte marciales": "martial arts",
    "artes marciales": "martial arts",
    #  "Artrópodos": "arthropods",
    #  "Arácnidos": "arachnids",
    "astrofísica": "astrophysics",
    "astrología": "astrology",
    "astronomía": "astronomy",
    "atletismo": "athletics",
    #  "Audiología": "audiology",
    #  "Automovilismo": "motoring",
    #  "Aves": "birds",
    #  "Bacterias": "bacteria",
    "danza": "dance",
    "baloncesto": "basketball",
    "balonmano": "handball",
    #  "Batería de cocina": "cookware",
    #  "Bebidas": "drinks",
    "billar": "billiards",
    "biología": "biology",
    "bioquímica": "biochemistry",
    "bolos": "bowling",
    "botánica": "botany",
    "béisbol": "baseball",
    #  "Caza": "hunt",
    #  "Cactus": "cactus",
    #  "Campamento": "camp",
    "cardiología": "cardiology",
    "carpintería": "carpentry",
    #  "Casos gramaticales": "grammatical cases",
    #  "Cereales": "cereals",
    #  "Cerrajería": "locksmith",
    "cetrería": "falconry",
    "ciclismo": "cycling",
    "ciencia": "science",
    "ciencia ficción": "science fiction",
    #  "Cine": "cinema",
    "cinegética": "hunting",
    "cinematografía": "cinematography",
    #  "Cinología": "cynology",
    "cirugía": "surgery",
    "ciudades": "cities",
    #  "Cnidarios": "cnidarians",
    #  "Colores": "colors",
    #  "Comercio": "trade",
    "comunicación": "communication",
    #  "Condimentos": "condiments",
    #  "Constelaciones": "constellations",
    "construcción": "construction",
    "contabilidad": "accounting",
    "continentes": "continents",
    #  "Cordilleras": "mountain ranges",
    "correos": "mail",
    #  "Cosmetología": "cosmetology",
    "cosmología": "cosmology",
    "cosmética": "cosmetics",
    "costura": "sewing",
    "cristianismo": "Christianity",
    "cronología": "chronology",
    #  "Crustáceos": "crustaceans",
    #  "Cubertería": "cutlery",
    #  "Cultura": "culture",
    "deporte": "sports",
    #  "Derecho": "right",
    #  "Dinosaurios": "dinosaurs",
    #  "Dioses": "gods",
    "diseño": "design",
    "días de la semana": "weekdays",
    "ecología": "ecology",
    "economía": "economics",
    #  "Edafología": "edaphology",
    "educación": "education",
    "electricidad": "electricity",
    "electromagnetismo": "electromagnetism",
    "electrónica": "electronics",
    #  "Elementos químicos": "chemical elements",
    #  "Emojis": "emoji",
    #  "Emoticonos": "emoticons",
    #  "Enfermedades": "diseases",
    "enología": "oenology",
    #  "Enseñanza": "teaching",
    "entomología": "entomology",
    #  "Equinodermos": "echinoderms",
    #  "Equitación": "horse riding",
    #  "Eras históricas": "historical eras",
    #  "Escultura": "sculpture",
    "esgrima": "fencing",
    #  "Especias": "spices",
    "estaciones": "seasons",
    "estadística": "statistics",
    #  "Estomatología": "stomatology",
    #  "Estética": "esthetic",
    "fabril": "manufacturing",
    #  "Fantasía": "fancy",
    #  "Farmacia": "pharmacy",
    "farmacología": "pharmacology",
    "feminismo": "feminism",
    #  "Festividades": "festivities",
    "ficción": "fiction",
    #  "Ficción fantástica": "fantasy fiction",
    "ficología": "phycology",
    "filatelia": "philately",
    "filosofía": "philosophy",
    "finanzas": "finance",
    "fisiología": "physiology",
    #  "Flores": "flowers",
    #  "Fobias": "phobias",
    "folclore": "folklore",
    "fonética": "phonetics",
    #  "Formas": "shapes",
    "fotografía": "photography",
    #  "Fraccionarios": "fractionals",
    #  "Frutas": "fruit",
    #  "Frutos": "fruits",
    "fármacos": "drugs",
    #  "Física": "physical",
    "fútbol": "soccer",
    #  "Ganadería": "cattle raising",
    #  "Gastronomía": "gastronomy",
    #  "Gentilicios": "gentilicios",
    "genética": "genetics",
    "geografía": "geography",
    "geología": "geology",
    "geometría": "geometry",
    #  "Gimnasia": "gym",
    #  "Glotónimos": "gluttonyms",
    "gramática": "grammar",
    #  "Granjería": "farming",
    #  "Guarismos": "figures",
    "halconería": "falconry",
    "herramientas": "tools",
    "heráldica": "heraldry",
    "hidrología": "hydrology",
    #  "Hierbas": "herbs",
    #  "Higiene": "hygiene",
    #  "Hipocorísticos": "hypocoristic",
    "historia": "history",
    #  "Historieta": "cartoon",
    #  "Hockey sobre césped": "field hockey",
    #  "Hongos": "fungus",
    "horticultura": "horticulture",
    #  "Hostelería": "hostelry",
    #  "Huesos": "bones",
    #  "Humanidades": "humanities",
    "ictiología": "ichthyology",
    #  "Lenguas": "languages",
    "imprenta": "printing",
    #  "Industria": "industry",
    "informática": "computing",
    "ingeniería": "engineering",
    "inmunología": "immunology",
    "insectos": "insects",
    #  "Instrumentos": "instruments",
    #  "Instrumentos de medición": "measurement tools",
    #  "Instrumentos musicales": "musical instruments",
    "interfaz gráfica de usuario": "graphical user interface",
    "internet": "Internet",
    #  "Invertebrados": "invertebrates",
    "islam": "Islam",
    #  "Islas": "islands",
    #  "Judaísmo": "judaism",
    "juegos": "games",
    #  "Juguetes": "toys",
    "lgbt": "LGBT",
    #  "Lagos": "lakes",
    "lexicografía": "lexicography",
    "lingüística": "linguistics",
    "literatura": "literature",
    #  "Logística": "logistics",
    #  "Lucha": "struggle",
    #  "Líquidos": "liquids",
    "lógica": "logic",
    "malabarismo": "juggling",
    "mamíferos": "mammals",
    #  "Mares": "seas",
    "náutica": "nautical",
    "matemática": "mathematics",
    #  "Materia": "subject",
    #  "Materiales": "materials",
    "mecánica": "mechanics",
    "medicina": "medicine",
    #  "Meses": "months",
    #  "Metales": "metals",
    "metalurgia": "metallurgy",
    "meteorología": "meteorology",
    "metrología": "metrology",
    "micología": "mycology",
    "microbiología": "microbiology",
    "milicia": "military",
    #  "Minerales": "minerals",
    "mineralogía": "mineralogy",
    "minería": "mining",
    "mitología": "mythology",
    "mobiliario": "furniture",
    #  "Moluscos": "mollusks",
    #  "Monedas": "coins",
    #  "Moneras": "moneras",
    #  "Montañas": "mountains",
    "muebles": "furniture",
    "música": "music",
    #  "Naipes": "playing cards",
    "natación": "swimming",
    #  "Naturaleza": "nature",
    #  "Nemátodos": "nematodes",
    "neurología": "neurology",
    "numismática": "numismatics",
    #  "Nutrición": "nutrition",
    #  "Números": "numbers",
    "ocultismo": "occultism",
    #  "Ocupaciones": "activities",
    #  "Océanos": "oceans",
    "odontología": "odontology",
    #  "Oficios": "trades",
    "oftalmología": "ophthalmology",
    "ornitología": "ornithology",
    "paleontología": "paleontology",
    "parapsicología": "parapsychology",
    #  "Parentesco": "relationship",
    #  "Partes del día": "parts of the day",
    "países": "countries",
    "peces": "fish",
    #  "Penínsulas": "peninsulas",
    "periodismo": "journalism",
    "perros": "dogs",
    #  "Personajes bíblicos": "biblical characters",
    #  "Personajes ficticios": "fictional characters",
    #  "Personajes históricos": "historical figures",
    "pesca": "fishing",
    #  "Pesos y medidas": "weights and measures",
    #  "Pintura": "paint",
    "planetas": "planets",
    #  "Plantas": "floors",
    #  "Platelmintos": "platyhelminths",
    #  "Platos": "dishes",
    #  "Poblaciones": "populations",
    "poesía": "poetry",
    #  "Política": "policy",
    "pragmática": "pragmatics",
    #  "Prehistoria": "prehistory",
    #  "Vestimenta": "outfit",
    #  "Profesiones": "professions",
    #  "Protistas": "protists",
    #  "Pseudociencias": "pseudosciences",
    "psicología": "psychology",
    "psiquiatría": "psychiatry",
    "química": "chemistry",
    "química orgánica": "organic chemistry",
    #  "Radiocomunicación": "radiocomunication",
    #  "Regiones": "regions",
    #  "Reinos biológicos": "biological kingdoms",
    "religión": "religion",
    #  "Relojería": "watchmaking",
    #  "Reptiles": "reptiles",
    #  "Restaurantes": "restaurants",
    #  "Retórica": "rhetoric",
    "rugby": "rugby",
    #  "Ríos": "rivers",
    #  "Sabores": "flavors",
    "salud": "health",
    #  "Saludos": "greetings",
    #  "Satélites": "satellites",
    #  "Seguridad": "security",
    #  "Semiología": "semiology",
    "semiótica": "semiotics",
    #  "Sentidos": "senses",
    #  "Sentimientos": "feelings",
    "serpientes": "snakes",
    "sexualidad": "sexuality",
    #  "Signos": "signs",
    #  "Signos ortográficos": "spelling signs",
    "silvicultura": "forestry",
    #  "Sociedad": "society",
    "sociología": "sociology",
    #  "Símbolos": "symbols",
    #  "Símbolos alquímicos": "alchemical symbols",
    #  "Símbolos astronómicos": "astronomical symbols",
    #  "Símbolos de unidades monetarias": "symbols of monetary units",
    "tauromaquia": "bullfighting",
    "taxonomía": "taxonomy",
    "teatro": "theater",
    "tecnología": "technology",
    "textiles": "textiles",
    "telecomunicaciones": "telecommunications",
    #  "Telecomunicación": "telecommunication",
    "tenis": "tennis",
    "teología": "theology",
    "termodinámica": "thermodynamics",
    "tiempo": "time",
    "tipografía": "typography",
    "topografía": "topography",
    #  "Topónimos": "toponyms",
    "transporte": "transport",
    #  "Tribus urbanas": "urban tribes",
    "turismo": "tourism",
    #  "Unidades de tiempo": "time units",
    #  "Urbanismo": "town planning",
    #  "Utensilios": "utensils",
    "vegetales": "vegetable",
    "vehículos": "vehicles",
    "verduras": "vegetable",
    #  "Vertebrados": "vertebrates",
    #  "Veterinaria": "vet",
    #  "Virtudes": "virtues",
    #  "Vivienda": "living place",
    #  "Waterpolo": "water polo",
    "zoología": "zoology",
    "zootomía": "zootomy",
    "álgebra": "algebra",
    #  "Árboles": "trees",
    "ética": "ethics",
    "óptica": "optics",
}


def translate_raw_tags(data: WordEntry):
    raw_tags = []
    for raw_tag in data.raw_tags:
        lower_raw_tag = raw_tag.lower()
        if lower_raw_tag in CSEM_TOPICS and hasattr(data, "topics"):
            data.topics.append(CSEM_TOPICS[lower_raw_tag])
        else:
            raw_tags.append(raw_tag)
    data.raw_tags = raw_tags
