# https://it.wiktionary.org/wiki/Wikizionario:Parti_del_discorso
# https://it.wiktionary.org/wiki/Categoria:Template_parti_del_discorso
# https://it.wiktionary.org/wiki/Categoria:Template_aggiornati
# https://it.wiktionary.org/wiki/Categoria:Template_per_gli_aggettivi
# https://it.wiktionary.org/wiki/Categoria:Template_altre_voci
POS_DATA = {
    "Acronimo / Abbreviazione": {"pos": "abbrev", "tags": ["abbreviation"]},
    "Articolo": {"pos": "article"},
    "Avverbio": {"pos": "adv"},
    "Classificatore": {"pos": "classifier"},
    "Congiunzione": {"pos": "conj"},
    "Espressione": {"pos": "phrase"},
    "Hanzi": {"pos": "character", "tags": ["hanzi"]},
    "Interiezione": {"pos": "intj"},
    "Pronuncia kanji": {"pos": "character", "tags": ["kanji"]},
    "Locuzione aggettivale": {"pos": "phrase", "tags": ["adjective"]},
    "Locuzione avverbiale": {"pos": "adv_phrase"},
    "Locuzione congiuntiva": {"pos": "phrase", "tags": ["conjunctive"]},
    "Locuzione interiettiva": {"pos": "phrase", "tags": ["interjection"]},
    "Locuzione nominale": {"pos": "phrase", "tags": ["noun"]},
    "Locuzione nominale, forma flessa": {
        "pos": "phrase",
        "tags": ["noun", "form-of"],
    },
    "Locuzione prepositiva": {"pos": "prep_phrase"},
    "Locuzione verbale": {"pos": "phrase", "tags": ["verb"]},
    "Nome proprio, forma flessa": {"pos": "name", "tags": ["form-of"]},
    "Nome proprio": {"pos": "name"},
    "Particella": {"pos": "particle"},
    "Posposizione": {"pos": "postp"},
    "Preposizione": {"pos": "prep"},
    "Pronome dimostrativo": {"pos": "pron", "tags": ["demonstrative"]},
    "Pronome indefinito": {"pos": "pron", "tags": ["indefinite"]},
    "Pronome interrogativo": {"pos": "pron", "tags": ["interrogative"]},
    "Pronome possessivo": {"pos": "pron", "tags": ["possessive"]},
    "Pronome relativo": {"pos": "pron", "tags": ["relative"]},
    "Pronome riflessivo": {"pos": "pron", "tags": ["reflexive"]},
    "Pronome": {"pos": "pron"},
    "Pronome, forma flessa": {"pos": "pron", "tags": ["form-of"]},
    "Sostantivo": {"pos": "noun"},
    "Sostantivo, forma flessa": {"pos": "noun", "tags": ["form-of"]},
    "Verbo": {"pos": "verb"},
    "Voce verbale": {"pos": "verb", "tags": ["form-of"]},
    "Lettera": {"pos": "character", "tags": ["letter"]},
    "Prefisso": {"pos": "prefix", "tags": ["morpheme"]},
    "Aggettivo": {"pos": "adj"},
    "Aggettivo dimostrativo": {"pos": "adj", "tags": ["demonstrative"]},
    "Aggettivo nominale": {"pos": "adj_noun"},
    "Aggettivo numerale": {"pos": "adj", "tags": ["numeral"]},
    "Aggettivo possessivo": {"pos": "adj", "tags": ["possessive"]},
    "Cifra": {"pos": "num"},
    "Prefissoide": {"pos": "prefix", "tags": ["morpheme"]},
    "Segno di interpunzione": {"pos": "punct", "tags": ["punctuation"]},
    "Suffisso": {"pos": "suffix", "tags": ["morpheme"]},
    "Aggettivo, forma flessa": {"pos": "adj", "tags": ["form-of"]},
    "Aggettivo numerale, forma flessa": {
        "pos": "adj",
        "tags": ["numeral", "form-of"],
    },
    "Abbreviazione in uso nelle chat": {
        "pos": "abbrev",
        "tags": ["abbreviation"],
    },
    "Codice / Simbolo": {"pos": "symbol"},
    "Carattere hiragana": {"pos": "character", "tags": ["hiragana"]},
    "Confisso": {"pos": "affix"},
    "Kanji": {"pos": "character", "tags": ["kanji"]},
    "Trascrizione": {"pos": "unknown", "tags": ["transcription", "form-of"]},
}


LINKAGE_SECTIONS = {
    "Sinonimi": "synonyms",
    "Contrari": "antonyms",
    "Derivati": "derived",
    "Termini correlati": "related",
    "Varianti": "related",
    "Alterati": "related",
    "Iponimi": "hyponyms",
    "Iperonimi": "hypernyms",
    "Da non confondere con": "related",
    "Proverbi e modi di dire": "proverbs",
    "Parole derivate": "derived",
}
