# Definitions of extracted parts of speech codes and a mapping from
# Wiktionary section titles to parts of speech.
#
# Copyright (c) 2018-2020 Tatu Ylonen.  See file LICENSE and https://ylonen.org

# This dictionary maps section titles in articles to parts-of-speech.  There
# is a lot of variety and misspellings, and this tries to deal with those.
part_of_speech_map = {
    "abbreviation": "abbrev",
    "acronym": "abbrev",
    "adjectival": "adj_noun",
    "adjectival noun": "adj_noun",
    "adjectival verb": "adj_verb",
    "adjective": "adj",
    "adjectuve": "adj",
    "adjectives": "adj",
    "adverb": "adv",
    "adverbs": "adv",
    "adverbial phrase": "adv_phrase",
    "affix": "affix",
    "adjective suffix": "affix",
    "article": "article",
    "character": "character",
    "circumfix": "circumfix",
    "circumposition": "circumpos",
    "classifier": "classifier",
    "clipping": "abbrev",
    "clitic": "clitic",
    "command form": "cmd",
    "command conjugation": "cmd_conj",
    "combining form": "combining_form",
    "comparative": "adj_comp",
    "conjunction": "conj",
    "conjuntion": "conj",
    "contraction": "abbrev",
    "converb": "converb",
    "counter": "counter",
    "determiner": "det",
    "diacritical mark": "character",
    "enclitic": "clitic",
    "enclitic particle": "clitic",
    "gerund": "gerund",
    "glyph": "character",
    "han character": "character",
    "han characters": "character",
    "ideophone": "noun",  # XXX
    "infix": "infix",
    "infinitive": "verb",
    "initialism": "abbrev",
    "interfix": "interfix",
    "interjection": "intj",
    "interrogative pronoun": "pron",
    "intransitive verb": "verb",
    "instransitive verb": "verb",
    "letter": "letter",
    "ligature": "character",
    "label": "character",
    "nom character": "character",
    "nominal nuclear clause": "clause",
    "νoun": "noun",
    "nouɲ": "noun",
    "noun": "noun",
    "nouns": "noun",
    "noum": "noun",
    "number": "num",
    "numeral": "num",
    "ordinal number": "ordinal",
    "participle": "verb",
    "particle": "particle",
    "past participle": "verb",
    "perfect expression": "verb",
    "perfection expression": "verb",
    "perfect participle": "verb",
    "personal pronoun": "pron",
    "phrasal verb": "phrasal_verb",
    "phrase": "phrase",
    "phrases": "phrase",
    "possessive determiner": "det",
    "possessive pronoun": "det",
    "postposition": "postp",
    "predicative": "predicative",
    "prefix": "prefix",
    "preposition": "prep",
    "prepositions": "prep",
    "prepositional expressions": "prep",
    "prepositional phrase": "prep_phrase",
    "prepositional pronoun": "pron",
    "present participle": "verb",
    "preverb": "verb",
    "pronoun": "pron",
    "proper noun": "name",
    "proper oun": "name",
    "proposition": "prep",  # Appears to be a misspelling of preposition
    "proverb": "proverb",
    "punctuation mark": "punct",
    "punctuation": "punct",
    "relative": "conj",
    "root": "root",
    "syllable": "character",
    "suffix": "suffix",
    "suffix form": "suffix",
    "symbol": "symbol",
    "transitive verb": "verb",
    "verb": "verb",
    "verbal noun": "noun",
    "verbs": "verb",
    "digit": "digit",   # I don't think this is actually used in Wiktionary
}

# Set of all possible parts-of-speech returned by wiktionary reading.
PARTS_OF_SPEECH = set(part_of_speech_map.values())
