# Special code related to the {{place|...} tag used to annotate place names.
#
# Copyright (c) 2018-2020 Tatu Ylonen.  See file LICENSE and https://ylonen.org

# Mapping from place prefixes in {{place|...}} templates to the type of place.
# Administrative divisions
#   - country
#   - province  (e.g. state, territory, prefecture, canton, voivodeship, oblast)
#   - municipality, city  (incl. borough, town, village, community)
#   - district  (generally smaller subdivisions of cities or small adm regions)
# Geographic divisions
#   - continent
#   - region (generally within a continent)
#   - area   (generally smaller than a region)
#   - place  (generally well-defined relatively small area/point)
# Types of geographic formations
#   - archipelago
#   - body-of-water  (includes seas, lakes, rivers)
place_prefixes = {
    "Hui and Tu autonomous county": "municipality",
    "Hui autonomous county": "municipality",
    "Korean autonomous prefecture": "province",
    "P": "province",
    "Tibetan autonomous prefecture": "province",
    "Yi autonomous prefecture": "province",
    "acomm": "municipality",
    "ar": "archipelago",
    "arch": "archipelago",
    "archipelago": "archipelago",
    "area": "area",
    "autonomous community": "municipality",
    "autonomous county": "municipality",
    "autonomous prefecture": "province",
    "autonomous province": "province",
    "autonomous region": "municipality",
    "autonomous republic": "province",
    "bay": "body-of-water",
    "bor": "municipality",
    "borough": "municipality",
    "c": "country",
    "c2": "country",
    "can": "province",
    "canton": "province",
    "carea": "district",
    "cc": "country",
    "cdp": "district",
    "CDP": "district",
    "census area": "municipality",
    "city": "city",
    "co": "municipality",
    "cobor": "municipality",
    "comarca": "district",
    "community": "municipality",
    "cont": "continent",
    "continent": "continent",
    "contregion": "region",
    "council area": "district",
    "country": "country",
    "county borough": "municipality",
    "county": "municipality",
    "county-level city": "city",
    "department": "province",
    "dept": "province",
    "direct-administered municipality": "municipality",
    "direct-administered municipality ": "municipality",
    "dist": "district",
    "distmun": "municipality",
    "district": "district",
    "district municipality": "municipality",
    "div": "province",
    "empire": "country",
    "en:country": "country",
    "en:island": "island",
    "en:province": "province",
    "en:state": "province",
    "glen": "village",
    "federal subject": "province",
    "forestry district": "area",
    "former township": "municipality",
    "house": "place",
    "isl": "island",
    "island": "island",
    "islands": "archipelago",
    "krai": "province",
    "league": "province",
    "lbor": "municipality",
    "lgarea": "area",
    "lgdist": "district",
    "lieutenancy area": "municipality",
    "local government district": "district",
    "m": "municipality",
    "macroregion": "region",
    "metbor": "municipality",
    "metropolis": "city",
    "metropolitan borough": "municipality",
    "moor": "district",
    "mountain": "place",
    "mun": "municipality",
    "municipality": "municipality",
    "muniplacity": "municipality",
    "neighborhood": "district",
    "obl": "province",
    "oblast": "province",
    "ocean": "body-of-water",
    "overseas department": "province",
    "p": "province",
    "par": "district",
    "parish": "district",
    "pen": "area",
    "penisula": "area",
    "pref": "province",
    "prefecture": "province",
    "prefecture-level": "city",
    "prefecture-level city": "city",
    "prov": "province",
    "prov;": "province",
    "province": "province",
    "r": "region",
    "range": "area",
    "region": "region",
    "regional unit": "municipality",
    "rep": "country",
    "republic": "country",
    "riv": "body-of-water",
    "river": "body-of-water",
    "rural township": "municipality",
    "s": "province",
    "sar": "municipality",
    "sea": "body-of-water",
    "special municipality": "municipality",
    "state": "province",
    "strait": "body-of-water",
    "sub-prefecture level city": "city",
    "sub-prefecture-level city": "city",
    "sub-provincial city": "city",
    "subdistrict": "district",
    "subprefecture": "province",
    "terr": "province",
    "territory": "province",
    "town": "municipality",
    "township": "municipality",
    "twp": "municipality",
    "unitary authority": "municipality",
    "urban township": "municipality",
    "valley": "region",
    "village": "district",
    "voi": "province",
    "voivodeship": "province",
    "ward": "district",
}
