# Lists of valid tags and mappings for tags canonicalization.
#
# Copyright (c) 2020-2021 Tatu Ylonen.  See file LICENSE and https://ylonen.org

# Mappings for tags in template head line ends outside parentheses
xlat_head_map = {
    "m": "masculine",
    "f": "feminine",
    "m/f": "masculine feminine",
    "n": "neuter",
    "c": "common",  # common gender in at least West Frisian
    "sg": "singular",
    "pl": "plural",
    "du": "dual",
    "inan": "inanimate",
    "anim": "animate",
    "pers": "person",  # XXX check what this really is used for? personal?
    "npers": "impersonal",
    "vir": "virile",
    "nvir": "nonvirile",
    "anml": "animal",
    "impf": "imperfective",
    "impf.": "imperfective",
    "pf": "perfective",
    "pf.": "perfective",
    "invariable": "invariable",
    "?": "",
    "1": "class-1",
    "1a": "class-1a",
    "2": "class-2",
    "2a": "class-2a",
    "3": "class-3",
    "4": "class-4",
    "5": "class-5",
    "6": "class-6",
    "7": "class-7",
    "8": "class-8",
    "9": "class-9",
    "9a": "class-9a",
    "10": "class-10",
    "10a": "class-10a",
    "11": "class-11",
    "12": "class-12",
    "13": "class-13",
    "14": "class-14",
    "15": "class-15",
    "16": "class-16",
    "17": "class-17",
    "1/2": "class-1 class-2",
    "3/4": "class-3 class-4",
    "5/6": "class-5 class-6",
    "7/8": "class-7 class-8",
    "9/10": "class-9 class-10",
    "m1": "masculine first-declension",
    "f2": "feminine second-declension",
    "m2": "masculine second-declension",
    "f3": "feminine third-declension",
    "m3": "masculine third-declension",
    "f4": "feminine fourth-declension",
    "m4": "masculine fourth-declension",
    "f5": "feminine fifth-declension",
    "m5": "masculine fifth-declension",
    "[uncountable]": "uncountable",
}

# Accepted uppercase tag values.  As tags these are represented with words
# connected by hyphens.
uppercase_tags = set([
    "AF",  # ??? what does this mean
    "ALUPEC",
    "Abagatan",
    "Abrahamic religions",
    "Absheron",
    "Abung/Kotabumi",
    "Abung/Sukadana",
    "Adlam",
    "Adyghe",
    "Aeolic",
    "Afi-Amanda",
    "Africa",
    "African-American Vernacular English",
    "Al-Andalus",
    "Ala-Laukaa",
    "Alak",
    "Algherese",
    "Alliancelles",
    "Alsatian",
    "American continent",
    "Amianan",
    "Amira",
    "Amrum",
    "Amur",
    "Anbarani",
    "Ancient",
    "Ancient Rome",
    "Andalucia",
    "Anglicised",
    "Anglicism",
    "Anglism",
    "Anglo-Norman",
    "Angola",
    "Aniwa",
    "Antanosy",
    "Antilles",
    "Appalachia",
    "Appalachian",
    "Arabic",
    "Aran",
    "Arawak",
    "Arbëresh",
    "Argentina",
    "Asalem",
    "Asalemi",
    "Ashkenazi Hebrew",
    "Atlantic Canada",
    "Aukštaitian",
    "Australia",
    "Australian",
    "Austria",
    "Austrian",
    "Avignon",
    "Ayt Ndhir",
    "Baan Nong Duu",
    "Bacheve",
    "Badiu",
    "Bahamas",
    "Bahasa Baku",
    "Baku",
    "Balearic",
    "Bangkok",
    "Bardez Catholic",
    "Batang",
    "Bavarian",
    "Beijing",
    "Belgium",
    "Belize",
    "Berlin",
    "Berlin-Brandenburg",
    "Beru",
    "Biblical Hebrew",
    "Biblical",
    "Bikol Legazpi",
    "Bikol Naga",
    "Bikol Tabaco",
    "Biscayan",
    "Bla-Brang",
    "Banawá",
    "Bo Sa-ngae",
    "Bodega",
    "Bogota",
    "Bohairic",
    "Bohemia",
    "Boholano",
    "Bokmål",
    "Bolivia",
    "Bologna",
    "Bolognese",
    "Bombay",
    "Borneo",
    "Bosnia Croatia",
    "Bosnia",
    "Bosnian",
    "Bosnian Croatian",
    "Bosnian Serbian",
    "Boston",
    "Brazil",
    "Brazilian",
    "Bressan",
    "Brest",
    "Britain",
    "British Army",
    "British Columbia",
    "British Isles",
    "British Royal Navy",
    "Buddhism",
    "Busan",
    "Bygdeå",
    "Byzantine",
    "Bzyb",
    "Béarn",
    "Caipira",
    "Caithness",
    "California",
    "Campidanese",
    "Canada",
    "Canadian",
    "Canadian English",
    "Canadian French",
    "Canadian Prairies",
    "Canary Islands",
    "Cantonese",
    "Cape Afrikaans",
    "Carakan",
    "Carcoforo",
    "Caribbean",
    "Carioca",
    "Castilian Spanish",
    "Castilian",
    "Catalonia",
    "Catholic",
    "Cebu",
    "Cebuano",
    "Central America",
    "Central Apulia",
    "Central Asia",
    "Central Scots",
    "Central Sweden",
    "Central and Southern Italy",
    "Central",
    "Chakavian",
    "Chanthaburi",
    "Chengdu",
    "Child US",
    "Chile",
    "China",
    "Chinese",
    "Chinese Character classification",
    "Chongqing",
    "Christian",
    "Chugoku",
    "Chūgoku",
    "Church of England",
    "Cieszyn Silesia",
    "Cincinnati",
    "Classical",
    "Classical Attic",
    "Classical Edessan",
    "Classical Indonesian",
    "Classical K'Iche",
    "Classical Latin",
    "Classical Persian",
    "Classical Sanskrit",
    "Classical studies",
    "Clay",
    "Closed ultima",
    "Coastal Min",
    "Cockney",
    "Cois Fharraige",
    "Cois Fharraige",
    "Colombia",
    "Common accent",
    "Commonwealth",
    "Connacht",
    "Connemara",
    "Contentin",
    "Copenhagen",
    "Cork",
    "Cornwall",
    "Costa Rica",
    "Cotentin",
    "Crimea",
    "Croatia",
    "Croatian",
    "Cuba",
    "Cuisnahuat",
    "Cusco",
    "Cyrillic",
    "Czech",
    "Czech Republic",
    "DR Congo",
    "Dalmatia",
    "Dari",
    "Daya",
    "Debri",
    "Deh Sarv",
    "Delhi",
    "Delhi Hindi",
    "Derbyshire",
    "Devanagari",
    "Devon",
    "Digor",
    "Dominican Republic",
    "Dominican Republic",
    "Doric",
    "Dundee",
    "Dutch",
    "Dêgê",
    "EU",
    "Early Middle English",
    "Early",
    "East Anglia",
    "East Armenian",
    "East Bengal",
    "East Coast",
    "East Midland",
    "East",
    "Eastern Armenian",
    "Eastern New England",
    "Eastern Syriac",
    "Eastern",
    "Ecclesiastical",
    "Ecuador",
    "Ecuadorian Kichwa",
    "Egypt",
    "Egyptian",
    "Ekagongo",
    "Ekavian",
    "El Salvador",
    "England",
    "English Midlands",
    "English",
    "Epic",
    "Esham",
    "Estuary English",
    "Europe",
    "European",
    "European Union",
    "European ortography",
    "Eurozone",
    "Fars",
    "Fayyumic",
    "Finland",
    "Flanders",
    "Flemish",
    "Florida",
    "Fluminense",
    "For transcription only",
    "Formazza",
    "Fragoria vesca",
    "France Quebec",
    "France",
    "Fredrikstad",
    "French",
    "From Old Northern French",
    "Föhr",
    "Föhr-Amrum",
    "Galgolitic",
    "Galitzish",
    "Galway",
    "Gan",
    "Gascon",
    "Gascony",
    "Gaspésie",
    "Gaúcho",
    "Gelders",
    "General American",
    "General Australian",
    "General Brazilian",
    "General Cebuano",
    "General New Zealand",
    "General South African",
    "Geordie",
    "Georgia",
    "German",
    "Germanic",
    "Germany",
    "Gheg",
    "Gherdëina",
    "Gipuzkoan",
    "Glagolitic",
    "Goeree-Overflakkee",
    "Gothenburg",
    "Gotland",
    "Goud Saraswat",
    "Greco-Bohairic",
    "Greek",
    "Greek Catholic",
    "Gronings",
    "Guadeloupean",
    "Guatemala",
    "Guernsey",
    "Gulf Arabic",
    "Gurmukhi",
    "Gyeongsang",
    "Hainanese",
    "Hakka",
    "Halchighol"
    "Hallig",
    "Hanoi",
    "Hanyuan",
    "Harak",
    "Harry Potter",
    "Hawaii",
    "Hawick",
    "Hebrew script",
    "Hejazi Arabic",
    "Hejazi",
    "Helgoland",
    "Hevaha",
    "Hijazi",
    "Hinduism",
    "Hokkien",
    "Honduras",
    "Hong Kong",
    "Hong'an",
    "Hoanya",
    "Hosso",
    "Hua",
    "Huế",
    "Hà Nội",
    "Hà Tĩnh",
    "Hössjö",
    "Hồ Chí Minh City",
    "IPA",
    "IUPAC name",
    "Iceland",
    "Ikavian",
    "Ijekavian",
    "Ilir",
    "In conjunct consonants",
    "India",
    "Indian English",
    "Indonesia",
    "Inland Min",
    "Inland Northern American",
    "Inner Mongolia",
    "Insular Scots",
    "Insular",
    "Internet",
    "Iran",
    "Iranian Persian",
    "Iraqi Hebrew",
    "Ireland",
    "Irish",
    "Iron",
    "Isfahan",
    "Islam",
    "Israel",
    "Italian Hebrew",
    "Italy",
    "Izalco",
    "Jabung",
    "Jainism",
    "Jakarta",
    "Jalalabad",
    "Jamaica",
    "Jamaican",
    "Jamaican creole",
    "Japan",
    "Jawi",
    "Jehovah's Witnesses",
    "Jèrriais",
    "Jersey",
    "Jewish Aramaic",
    "Jewish Babylonian Aramaic",
    "Jewish Palestinian Aramaic",
    "Jewish",
    "Jianghuai Mandarin",
    "Jicalapa",
    "Jilu Mandarin",
    "Jin Mandarin",
    "Johannesburg",
    "Johor-Selangor",
    "Johore",
    "Judaism",
    "Jyutping",
    "Kabul",
    "Kabuli",
    "Kadaru",
    "Kagoshima",
    "Kaiwaligau Ya",
    "Kajkavian",
    "Kalaw Kawaw Ya",
    "Kalaw Lagaw Ya",
    "Kalianda",
    "Kalix",
    "Kamino",
    "Kampong Ayer",
    "Kanchanaburi",
    "Kandahar",
    "Kansai",
    "Karabakh",
    "Karwari",
    "Katharevousa",
    "Kautokeino",
    "Kayu Agung",
    "Kayu Agung Asli",
    "Kayu Agung Pendatang",
    "Kaw Kyaik",
    "Kazym",
    "Kedayan",
    "Kent",
    "Kentish",
    "Kenya",
    "Kernowek Standard",
    "Kerry",
    "Khorasan",
    "Khun villages",
    "Kiambu",
    "Kinyarwanda",
    "Kirundi",
    "Koine",
    "Kong Loi village",
    "Kong Loi villages",
    "Kota Agung",
    "Krui",
    "Kulkalgau Ya",
    "Kuritiba",
    "Kuwaiti Gulf Arabic",
    "Kuzarg",
    "Kyoto",
    "Kyūshū",
    "LÚ",
    "La Up village",
    "Lamphun Province",
    "Languedoc",
    "Late Bohairic",
    "Late Egyptian",
    "Late Latin",
    "Late Middle English",
    "Late Old French",
    "Late Old Frisian",
    "Late West Saxon",
    "Late",
    "Latin America",
    "Latin",
    "Latinate",
    "Latinism",
    "Lebanese Arabic",
    "Lengadocian",
    "Levantine Arabic",
    "Lewis",
    "Leyte",
    "Lhasa",
    "Liechtenstein",
    "Limousin",
    "Limuru",
    "Literary affectation",
    "Litvish",
    "Liverpudlian",
    "Logudorese",
    "Lojban",
    "Loli",
    "Lombardy",
    "London",
    "Lorraine",
    "Louisiana",
    "Low Prussian",
    "Low Sorbian",
    "Luleå",
    "Luserna",
    "Lyon",
    "Lövånger",
    "Mahuizalco",
    "Main dialectal variations",
    "Maine",
    "Mainland China",
    "Malaysia",
    "Malaysian English",
    "Mamluk-Kipchak",
    "Mandarin",
    "Many eastern and northern dialects",
    "Martinican",
    "Martinican Creole",
    "Mary-marry-merry distinction",
    "Mary-marry-merry merger",
    "Marxism",
    "Masarm",
    "Mayo",
    "McCune-Reischauer-chŏn",
    "Medan",
    "Mediaeval",
    "Medieval",
    "Medieval Greek",
    "Medieval Latin",
    "Medio-Late Egyptian",
    "Melinting",
    "Menggala/Tulang Bawang",
    "Mercian",
    "Mexico",
    "Mfom",
    "Microsoft Azure",
    "Mid Northern Scots",
    "Mid Northern",
    "Mid",
    "Mid-Atlantic",
    "Middle Ages",
    "Middle Cornish",
    "Middle Egyptian",
    "Middle",
    "Midland American English",
    "Midlands",
    "Midwestern US",
    "Milan",
    "Min Bei",
    "Min Dong",
    "Min Nan",
    "Mineiro",
    "Mistralian",
    "Mizrahi Hebrew",
    "Modern Armenian",
    "Modern Israeli Hebrew",
    "Modern Israeli",
    "Modern Latin",
    "Modern Turkish",
    "Modern",
    "Moldavia",
    "Mongolian script",
    "Montreal",
    "Mooring",
    "Mormonism",
    "Moroccan",
    "Morocco",
    "Moscow",
    "Mosetén",
    "Mozambique",
    "MMpakwithi",
    "Multicultural London English",
    "Munster",
    "Murang'a",
    "Muslim",
    "Münsterländisch",
    "Myanmar",
    "Myanmar",
    "Nanchuan",
    "Naples",
    "Navajo",
    "Navarrese",
    "Navarro-Lapurdian",
    "Navy",
    "Nazism",
    "Ndia",
    "Nepal",
    "Netherlands",
    "Nevada",
    "New Age",
    "New England",
    "New Jersey",
    "New Latin",
    "New York City",
    "New York",
    "New Zealand",
    "Newfoundland",
    "Nicaragua",
    "Nigeria",
    "Nordestino",
    "Norfolk",
    "Normandy",
    "Norse",
    "North Afar",
    "North America",
    "North American",
    "North Brazil",
    "North East England",
    "North German",
    "North Korea",
    "North Levantine",
    "North Northern Scots",
    "North Northern",
    "North Northern",
    "North Wales",
    "North and East of the Netherlands",
    "North",
    "Northeast Brazil",
    "Northeastern Brazil",
    "Northeastern",
    "Northern California",
    "Northern Catalan",
    "Northern Crimea",
    "Northern England",
    "Northern English",
    "Northern Germany",
    "Northern Ireland",
    "Northern Italy",
    "Northern Mandarin",
    "Northern Manx",
    "Northern Middle English",
    "Northern Scots",
    "Northern UK",
    "Northern US",
    "Northern Yiddish",
    "Northern Zazaki",
    "Northern",
    "Northamptonshire",
    "Northumbria",
    "Northwestern",
    "Nde",
    "Nfom",
    "Nkim",
    "Nkum",
    "Nselle",
    "Nta",
    "Nyeri",
    "Nynorak",
    "Nynorsk",
    "Occitania",
    "Old Bohairic",
    "Old Chamorro",
    "Old Egyptian",
    "Old Northern French",
    "Old Tagalog",
    "Oliti",
    "Ontario",
    "Orcadian",
    "Orkney",
    "Oslo",
    "Pa Pae village",
    "Paderbornish",
    "Paderbornisch",
    "Pahang",
    "Pak Kret District",
    "Pakistan",
    "Palatine",
    "Palestinian",
    "Panama",
    "Paraguay",
    "Paris",
    "Parisian",
    "Parts of south Jeolla",
    "Paulistano",
    "Pays de Bray",
    "Pays de Caux",
    "Peking",
    "Pennsylvania",
    "Periphrastic conjugations",
    "Persian Gulf",
    "Peru",
    "Peshawar",
    "Philadelphia",
    "Philippine",
    "Philippines",
    "Pinyin",
    "Piteå",
    "Polari",
    "Polish",
    "Portugal",
    "Portugal",
    "Possesse",
    "Poylish",
    "Poznań",
    "Pre-Hebrew",
    "Prokem",
    "Protestant",
    "Provençal",
    "Pubian",
    "Puerto Rico",
    "Puter",
    "Vallander",
    "Quakerism",
    "Quanzhou",
    "Quebec City",
    "Quebec",
    "Quetta",
    "Ranau",
    "Received Pronunciation",
    "Renshou",
    "Revived Late Cornish",
    "Revived Middle Cornish",
    "Revived",
    "Rhodesia",
    "Riau-Lingga",
    "Rigveda",
    "Ring",
    "Rio Grande De Sul",
    "Rio de Janeiro",
    "Rioplatense",
    "Ripuarian",
    "Ritsu",
    "Rogaland",
    "Roman",
    "Roman Catholic",
    "Roman Empire",
    "Rouen",
    "Rumantsch Grischun",
    "Rumi",
    "Rumy",
    "Rundi",
    "Russia",
    "Russian",
    "Russianism",
    "Rwanda",
    "Rālik",
    "Rāṛha",
    "Rōmaji",
    "SK Standard",
    "SW England",
    "São-Paulo",
    "Saarve",
    "Sahidic",
    "Saint Ouen",
    "Saint Petersburg",
    "Sakhalin",
    "San Juan Quiahije",
    "Sanskrit",
    "Santiago",
    "São Vicente",
    "Sappada",
    "Sark",
    "Sauerländisch",
    "Sauris",
    "Savoyard",
    "Sawndip",
    "Scientific Latin",
    "Scotland",
    "Scottish",
    "Scouse",
    "Serbia",
    "Serbian",
    "Servia",
    "Sette Comuni",
    "Shahmukhi",
    "Shapsug",
    "Sheffield",
    "Sheng",
    "Shephardi Hebrew",
    "Shetland",
    "Shetlandic",
    "Shia",
    "Shikoku",
    "Shin",
    "Shingon Buddhism",
    "Shropshire",
    "Shuri-Naha",
    "Shuryshkar",
    "Sibe",
    "Sichuanese",
    "Sikhism",
    "Silesian",
    "Simplified",
    "Singapore English",
    "Singapore",
    "Sino-Korean",
    "Sino-Japanese",
    "Sistani",
    "Skellefteå",
    "Skiri",
    "Slovincian",
    "Space Force",
    "Soikkola",
    "Sori",
    "Sotavento",
    "Souletin",
    "South Afar",
    "South Africa",
    "South African",
    "South America",
    "South American English",
    "South Asia",
    "South Azerbaijani",
    "South Brazil",
    "South German",
    "South Korea",
    "South Levantine",
    "South Northern Scots",
    "South Scots",
    "South Wales",
    "South",
    "Southeastern",
    "Southern Brazil",
    "Southern England",
    "Southern Italy",
    "Southern Manx",
    "Southern Middle English",
    "Southern Quechua",
    "Southern Scotland",
    "Southern Scots",
    "Southern Spain",
    "Southern US",
    "Southern Yiddish",
    "Southern Zazaki",
    "Southern",
    "Southwestern",
    "Southwestern Mandarin",
    "Spain",
    "Spanish",
    "Sri Lanka",
    "Standard Cornish",
    "Standard East Norwegian",
    "Standard German of Switzerland",
    "Standard German",
    "Standard Hlai",
    "Standard Sicilian",
    "Standard Tagalog",
    "Standard Zhuang",
    "Standard",
    "Stavanger",
    "Suizhou",
    "Sukai",
    "Sukau",
    "Sungkai",
    "Sunni",
    "Surgut",
    "Surigaonon",
    "Suriname",
    "Surmiran",
    "Sursilvan",
    "Sutsilvan",
    "Sweden",
    "Swiss German",
    "Swiss",
    "Switzerland",
    "Sylt",
    "Syriac",
    "Syrian Hebrew",
    "São Paulo",
    "São Vicente",
    "TV",
    "Tabriz",
    "Tainan",
    "Taipei",
    "Taiwan",
    "Taiwanese Hokkien",
    "Taiwanese Mandarin",
    "Tajik",
    "Talang Padang",
    "Tao",
    "Tasmania",
    "Tasmanian",
    "Tavastia",
    "Tehran",
    "Tehrani",
    "Tendai or Kegon Buddhism",
    "Teochew",
    "Teotepeque",
    "Texas",
    "Thailand",
    "Thanh Chương",
    "The Hague",
    "Thung Luang village",
    "Thung Luang",
    "Tiberian Hebrew",
    "Timor-Leste",
    "Tokyo",
    "Tongzi",
    "Tosk",
    "Toulouse",
    "Traditional",
    "Transylvania",
    "Trat",
    "Tredici Communi",
    "Trinidad and Tobago",
    "Tyneside",
    "UK with /ʊ/",
    "UK",
    "Ulu",
    "Upper Silesia",
    "US with /u/",
    "US",
    "US-Inland North",
    "US-merged",
    "Ukrainish",
    "Ukraynish",
    "Ulaanbaatar",
    "Ulster Scots",
    "Ulster",
    "Umeå",
    "Unified",
    "Unix",
    "Upper RP Triphthong Smoothing",
    "Uri",
    "Uruguay",
    "Uyghurjin",
    "Vaiśeṣika",
    "Valencia",
    "Valencian",
    "Vallander",
    "Vancouver Island",
    "Vaṅga",
    "Vedic",
    "Venezuela",
    "Vidari",
    "Vietnam",
    "Vinh",
    "Virginia",
    "Vivaro-Alpine",
    "Vosges",
    "Wade-Giles",
    "Wales",
    "Wallonia",
    "Wardak",
    "Waterford",
    "Wazirwola",
    "Welsh English",
    "Wengzhou Wu",
    "West Armenian",
    "West Bengal",
    "West Cork",
    "West Country",
    "West Kerry",
    "West Midlands",
    "West Muskerry",
    "West",
    "Western Armenian",
    "Western Quebec",
    "Western Rumelia",
    "Western Syriac",
    "Western",
    "Westminster system",
    "Westphalia",
    "Westphalian",
    "Windesi",
    "Witzapan",
    "Wood",
    "World War I",
    "Written Form",
    "Wu",
    "Wuhan",
    "WW2 air pilots' usage",
    "X-system",
    "Xiamen",
    "Xiang",
    "YIVO",
    "Yajurveda chanting",
    "Yale",
    "Yale-cen",
    "Yanhe",
    "Yemenite Hebrew",
    "Yichang",
    "Yiddish-influenced",
    "Yintyingka",
    "Ylä-Laukaa",
    "Yongshan",
    "Yorkshire",
    "Zen and Pure Land Buddhism",
    "Zhangzhou",
    "Zimbabwe",
    "Zinacantán",
    "Zurich",
    "Zêkog",
    "Överkalix",
    "central and northeastern Switzerland",
    "coastal Min",
    "continental Normandy",
    "feudal Britain",
    "outside Northumbria",
    "regionally African American Vernacular",
    "southern Moselle Franconian",
    "west Sweden",
    "post-Classical",
])


# General mapping for linguistic tags.  Value is a string of space-separated
# tags, or list of alternative sets of tags.  Alternative forms in the same
# category can all be listed in the same string (e.g., multiple genders).
# XXX should analyze imperfect vs. imperfective - are they just used in
# different languages, or is there an actual difference in meaning?
xlat_tags_map = {
    "m.": "masculine",
    "male": "masculine",
    "f.": "feminine",
    "fem.": "feminine",
    "female": "feminine",
    "indef.": "indefinite",
    "gen.": "genitive",
    "impf.": "imperfective",
    "pf.": "perfective",
    "trans.": "transitive",
    "unc": "uncountable",
    "abbreviated": "abbreviation",
    "diminutives": "diminutive",
    "†-tari": "-tari",
    "†-nari": "-nari",
    "cangjie input": "cangjie-input",
    "RP": "Received-Pronunciation",
    "BR": "Brazil",
    "Brasil": "Brazil",
    "Brazilian Portuguese": "Brazil",
    "FR": "France",
    "IT": "Italy",
    "CAN": "Canada",
    "AU": "Australia",
    "AUS": "Australia",
    "AusE": "Australia",
    "NYC": "New-York-City",
    "CA": "Canada",
    "AT": "Austria",
    "GA": "General-American",
    "NV": "Navajo",
    "UK male": "UK",
    "UK female": "UK",
    "GB": "UK",
    "EN": "UK",
    "IN": "India",
    "PRC": "China",
    "BG": "Bulgaria",
    "DE": "Germany",
    "NL": "Netherlands",
    "NZ": "New Zealand",
    "PT": "Portugal",
    "BOL": "Bolivia",
    "U.S.A.": "US",
    "U.S.": "US",
    "United States": "US",
    "Québec": "Quebec",
    "Classic Persian": "Classical-Persian",
    "Vivaro-alpine": "Vivaro-Alpine",
    "Mooring and Hallig": "Mooring Hallig",
    "Zürich": "Zurich",
    "Uk": "UK",
    "US/UK": "US UK",  # XXX leave separate
    "USA": "US",
    "Audio": "",
    "Noun": "noun",
    "Adjective": "adjective",
    "Verb": "verb",
    "Poetic": "poetic",
    "Colloquial": "colloquial",
    "Slang": "slang",
    "including": "",
    "Dialectal": "dialectal",
    "Dialect: Oslo": "Oslo",
    "Canada: Ontario": "Ontario",
    "Canada: British Columbia": "British-Columbia",
    "GenAm": "General American",
    "Greco-Bohairic Pronunciation": "Greco-Bohairic",
    "Greco-Bohairic pronunciation": "Greco-Bohairic",
    "Conservative RP": "Received-Pronunciation",
    "Received Prononunciation": "Received-Pronunciation",
    "North American also": "North-American",
    "Cois Fharraige also": "Cois-Fharraige",
    "Sawndip forms": "Sawndip",
    "Sawndip form": "Sawndip",
    "old orthography": "archaic",
    "Maine accent": "Maine",
    "Bosnia Serbia": "Bosnian-Serbian",
    "MLE": "Multicultural-London-English",
    "AAVE": "African-American-Vernacular-English",
    "Early ME": "Early-Middle-English",
    "Northern ME": "Northern-Middle-English",
    "Southern ME": "Southern-Middle-English",
    "Late ME": "Late-Middle-English",
    "Spanish given name": "Spanish proper-noun",
    "St. Petersburg or dated": "Saint-Petersburg dated",
    "Irregular reading": "irregular",
    "Argentina and Uruguay": "Argentina Uruguay",
    "Argentina Uruguay": "Argentina Uruguay",
    "Southern US folk speech": "Southern-US dialectal",
    "the Eurozone": "Eurozone",
    "Phoneme": "phoneme",
    "Vowel": "phoneme",
    "Consonant": "phoneme",
    "Name of letter": "name",
    "nation's name": "name",
    "proprietary name": "name",
    "Vulgar": "vulgar",
    "Spoken": "colloquial",
    "Syllable initial": "syllable-initial",
    "Syllable final": "syllable-final",
    "internet": "Internet",
    "online": "Internet",
    "instant messaging": "Internet",
    "cot-caught merged": "cot-caught-merger",
    "cot-caught merger": "cot-caught-merger",
    "prefix before comparative forms": "prefix with-comparative",
    "countable and uncountable": "countable uncountable",
    "masculine and feminine plural": "masculine feminine plural",
    "definite singular and plural": "definite singular plural",
    "plural and definite singular attributive":
    ["plural attributive", "definite singular attributive"],
    "oblique and nominative feminine singular":
    "oblique nominative feminine singular",
    "feminine and neuter plural": "feminine neuter plural",
    "feminine and neuter": "feminine neuter",
    "feminine and neuter plural": "feminine neuter plural",
    "masculine and feminine": "masculine feminine",
    "masculine and neuter": "masculine neuter",
    "masculine and plural": "masculine plural",
    "female and neuter": "feminine neuter",
    "singular and plural": "singular plural",
    "plural and weak singular": ["plural", "weak singular"],
    "dative-directional": "dative directional",
    "preterite and supine": "preterite supine",
    "genitive and dative": "genitive dative",
    "genitive and plural": "genitive plural",
    "dative and accusative": "dative accusative",
    "accusative/illative": "accusative illative",
    "dative and accusative singular": "dative accusative singular",
    "simple past and past participle": ["simple past", "past participle"],
    "taking a past participle": "with-past-participle",
    "literary or in compounds": "literary in-compounds",
    "certain compounds": "in-compounds idiomatic",
    "literary or archaic": "literary archaic",
    "literary or dialectal": "literary dialectal",
    "simple past": "simple past",
    "simple present": "simple present",
    "with verb in simple tense": "with-simple",
    "for most verbs": "usually",
    "genitive/dative": "genitive dative",
    "dative/locative": "dative locative",
    "dative/instrumental": "dative instrumental",
    "genitive/dative/locative": "genitive dative locative",
    "genitive/dative/ablative": "genitive dative ablative",
    "dative/ablative/locative": "dative ablative locative",
    "ablative/vocative": "ablative vocative",
    "ablative/locative": "ablative locative",
    "ablative/instrumental": "ablative instrumental",
    "dative/ablative": "dative ablative",
    "genitive/instrumental/locative": "genitive instrumental locative",
    "genitive/dative/locative/vocative": "genitive dative locative vocative",
    "genitive/dative/instrumental/prepositional":
    "genitive dative instrumental prepositional",
    "+ prepositional case": "with-prepositional",
    "+prepositional": "with-prepositional",
    "+ por": "with-por",
    "accusative/instrumental": "accusative instrumental",
    "dative/adverbial case": "dative adverbial",
    "dative/genitive": "dative genitive",
    "dative/genitive/instrumental": "dative genitive instrumental",
    "dative/accusative": "dative accusative",
    "dative/accusative/locative": "dative accusative locative",
    "genitive/accusative/prepositional":
    "genitive accusative prepositional",
    "genitive/dative/accusative": "genitive dative accusative",
    "genitive/animate accusative": ["genitive", "animate accusative"],
    "accusative plural and genitive plural": "accusative genitive plural",
    "first/second-declension adjective":
    "first-declension second-declension adjective",
    "first/second-declension participle":
    "first-declension second-declension participle",
    "class 9/10": "class-9 class-10",
    "class 5/6": "class-5 class-6",
    "class 3/4": "class-3 class-4",
    "class 7/8": "class-7 class-8",
    "class 1/2": "class-1 class-2",
    "class 11/10": "class-11 class-10",
    "refl": "reflexive",
    "first/second declension": "first-declension second-declension",
    "first/second-declension suffix":
    "first-declension second-declension suffix",
    "first/second-declension numeral plural only":
    "first-declension second-declension numeral plural-only",
    "possessive (with noun)": "possessive with-noun",
    "possessive (without noun)": "possessive without-noun",
    "informal 1st possessive": "informal first-person possessive",
    "formal or literary": "formal literary",
    "formal and written": "formal literary",
    "impolite 2nd possessive": "informal second-person possessive",
    "casual": "informal",
    "strong personal": "strong personal pronoun",
    "weak personal": "weak personal pronoun",
    "with adjective or adjective-phrase complement": "with-adjective",
    "with accusative or dative": "with-accusative with-dative",
    "with accusative or genitive": "with-accusative with-genitive",
    "with accusative or ablative": "with-accusative with-ablative",
    "genitive or accusative": ["genitive accusative"],
    "genitive of personal pronoun": "genitive personal pronoun",
    "nominative and accusative definite singular":
    "nominative accusative definite singular",
    "+ genitive": "with-genitive",
    "+ genitive possessive suffix or elative":
    "with-genitive with-possessive-suffix with-elative",
    "+ genitive-accusative": "with-genitive",
    "+ partitive or (less common) possessive suffix":
    "with-partitive with-possessive-suffix",
    "+ allative": "with-allative",
    "[an (about) + accusative]": "with-an with-accusative",
    "less common": "uncommon",
    "less frequently": "uncommon",
    "no perfect or supine stem": "no-perfect no-supine",
    "adverbial locative noun in the pa, ku, or mu locative classes":
    "adverbial locative",
    "comparative -": "no-comparative",
    "superlative -": "no-superlative",
    "1 declension": "first-declension",
    "4 declension": "fourth-declension",
    "5th declension": "fifth-declension",
    "feminine ? declension": "feminine",
    "masculine ? declension": "masculine",
    "1st declension": "first-declension",
    "2nd declension": "second-declension",
    "3rd declension": "third-declension",
    "4th declension": "fourth-declension",
    "2nd-person": "second-person",
    "1st-person": "first-person",
    "3rd-person": "third-person",
    "1st person": "first-person",
    "2nd person": "second-person",
    "3rd person": "third-person",
    "plural inv": "plural invariable",
    "plural not attested": "no-plural",
    "no plural forms": "no-plural",
    "used only predicatively": "not-attributive",
    "only predicative": "not-attributive",
    "predicatively": "predicative",
    "present tense": "present",
    "past tense": "past",
    "feminine counterpart": "feminine",
    "masculine counterpart": "masculine",
    "passive counterpart": "passive",
    "active counterpart": "active",
    "basic stem form": "stem",
    "no supine stem": "no-supine",
    "no perfect stem": "no-perfect",
    "construct state": "construct",
    "construct form": "construct",
    "uppercase": "upper-case",
    "lowercase": "lower-case",
    "phonemic reduplicative": "reduplicated",
    "neutrally formal": "somewhat formal",
    "objective case": "objective",
    "first person": "first-person",
    "second person": "second-person",
    "third person": "third-person",
    "genitive case": "genitive",
    "dative case": "dative",
    "accusative case": "accusative",
    "ergative cases": "ergative",
    "absolutive case": "absolutive",
    "genitive unattested": "no-genitive",
    "genitive -": "no-genitive",
    "nominative plural -": "no-nominative-plural",
    "colloquially also feminine": "colloquial feminine",
    "rare/awkward": "rare",
    "rarefied": "rare",
    "rarely": "rare",
    "personified": "person",
    "found only in the imperfective tenses": "no-perfect",
    "third plural indicative": "third-person plural indicative",
    "defective verb": "defective",
    "+ active 3rd infinitive in elative": "with-third-infinitive-elative",
    "+ active 3rd infinitive in illative": "with-third-infinitive-illative",
    "+ illative, allative, (verbs) 3rd infinitive in illative":
    "with-illative with-allative with-third-infinitive-illative",
    "+ partitive + 3rd person singular": "with-partitive",
    "3rd possessive": "third-person possessive",
    "active voice": "active",
    "+ infinitive": "with-infinitive",
    "+ a + infinitive": "with-a with-infinitive",
    "+ indicative mood": "with-indicative",
    "+ conditional mood": "with-conditional",
    "plus genitive": "with-genitive",
    "+ genitive": "with-genitive",
    "+genitive": "with-genitive",
    "+ genitive case": "with-genitive",
    "genitive +": "with-genitive",
    "genitive or possessive suffix +": "with-genitive with-possessive-suffix",
    "with genitive case": "with-genitive",
    "with genitive": "with-genitive",
    "+dative": "with-dative",
    "+ dative case": "with-dative",
    "+ dative": "with-dative",
    "+ historic dative": "with-dative historic",
    "only with adjectives": "with-adjective",
    "plus dative": "with-dative",
    "plus dative case": "with-dative",
    "with dative": "with-dative",
    "with dative case": "with-dative",
    "+ accusative": "with-accusative",
    "+ accusative case": "with-accusative",
    "+accusative": "with-accusative",
    "with accusative case": "with-accusative",
    "with accusative": "with-accusative",
    "plus accusative": "with-accusative",
    "governs the accusative": "with-accusative",
    "+ partitive": "with-partitive",
    "+ partitive + vastaan": "with-partitive",
    "+partitive": "with-partitive",
    "with partitive case": "with-partitive",
    "plus partitive": "with-partitive",
    "with partitive": "with-partitive",
    "+ablative": "with-ablative",
    "+ ablative": "with-ablative",
    "with ablative case": "with-ablative",
    "plus ablative": "with-ablative",
    "with ablative": "with-ablative",
    "+ subjunctive": "with-subjunctive",
    "+subjunctive": "with-subjunctive",
    "plus subjunctive": "with-subjunctive",
    "with subjunctive": "with-subjunctive",
    "+ instrumental": "with-instrumental",
    "+instrumental": "with-instrumental",
    "+ instrumental case": "with-instrumental",
    "with instrumental case": "with-instrumental",
    "with instrumental": "with-instrumental",
    "plus instrumental": "with-instrumental",
    "with instrumental or genitive case": "with-instrumental with-genitive",
    "with instrumental or dative case": "with-instrumental with-dative",
    "+ locative": "with-locative",
    "+ locative case": "with-locative",
    "with locative": "with-locative",
    "+ illative": "with-illative",
    "+ translative": "with-translative",
    "+ negative adjective in translative": "with-translative",
    "with negation": "with-negation",
    "+ adessive": "with-adessive",
    "+ adessive or illative": "with-adessive with-illative",
    "+absolutive": "with-absolutive",
    "+ absolutive": "with-absolutive",
    "with absolutive case": "with-absolutive",
    "with absolutive": "with-absolutive",
    "+ absolutive case": "with-absolutive",
    "plus absolutive": "with-absolutive",
    "+elative": "with-elative",
    "+ elative": "with-elative",
    "+ [elative]": "with-elative",
    "with elative case": "with-elative",
    "with elative": "with-elative",
    "plus elative": "with-elative",
    "+ comparative": "with-comparative",
    "+objective": "with-objective",
    "+ objective": "with-objective",
    "with objective case": "with-objective",
    "with objective": "with-objective",
    "plus objective": "with-objective",
    "+ present form": "with-present",
    "+ noun phrase] + subjunctive (verb)":
    "with-noun-phrase with-subjunctive",
    "with noun phrase": "with-noun-phrase",
    "+ [nounphrase] + subjunctive":
    "with-noun-phrase with-subjunctive",
    "+ number": "with-number",
    "with number": "with-number",
    "optative mood +": "with-optative",
    "p-past": "passive past",
    "ppp": "passive perfect participle",
    "not used in plural form": "no-plural",
    "not declined": "indeclinable",
    "not often used": "rare",
    "interrogative adverb": "interrogative adverb",
    "perfect tense": "perfect",
    "intensive": "emphatic",
    "intensifier": "emphatic",
    "changed conjunct form": "conjunct",
    "biblical hebrew pausal form": "pausal",
    "emphatic form": "emphatic",
    "emphatically": "emphatic",
    "emphatical": "emphatic",
    "standard form": "standard",
    "augmented form": "augmented",
    "active form": "active",
    "passive form": "passive",
    "mutated form": "mutated",
    "auxiliary verb": "auxiliary",
    "modal auxiliary verb": "auxiliary modal",
    "transitive verb": "transitive",
    "intransitive verb": "intransitive",
    "transitive or intransitive": "transitive intransitive",
    "male equivalent": "masculine",
    "in compounds": "in-compounds",
    "in combination": "in-compounds",
    "attribute": "attributive",
    "in the past subjunctive": "past subjunctive",
    "use the subjunctive tense of the verb that follows": "with-subjunctive",
    "kyūjitai form": "kyūjitai",
    "shinjitai kanji": "shinjitai",
    "dialectical": "dialectal",
    "dialectal or archaic": "dialectal archaic",
    "dialect": "dialectal",
    "possibly obsolete": "archaic",
    "antiquated": "archaic",
    "19th century": "archaic",
    "dated or regional": "archaic regional",
    "dated or archaic": "archaic",
    "common and polite term": "polite",
    "most common but potentially demeaning term": "possibly derogatory",
    "highly academic": "literary",
    "highly irregular": "irregular",
    "academic": "literary",
    "archaic ortography": "archaic",
    "in the plural": "plural-only",
    "derogative": "derogatory",
    "disparaging": "derogatory",
    "collective sense": "collective",
    "relatively rare": "rare",
    "very informal": "informal",
    "with a + inf.": "with-a with-infinitive",
    "with di + inf.": "with-di with-infinitive",
    "with che + subj.": "with-che with-subjunctive",
    "with inf.": "with-infinitive",
    "with infinitive": "with-infinitive",
    "with following infinitive": "with-infinitive",
    # XXX re-enable "~ се": "with-ce",
    "strong/mixed": "strong mixed",
    "strong/weak/mixed": "strong weak mixed",
    "weak/mixed": "weak mixed",
    "weak verb": "weak-verb",
    "auxiliary sein": "with-sein",
    "nominative/accusative": "nominative accusative",
    "masculine/feminine": "masculine feminine",
    "masculine/neuter": "masculine neuter",
    "present/future": "present future",
    "future/present": "present future",
    "present/aoriest": "present aorist",
    "superlative degree": "superlative",
    "comparative degree": "comparative",
    "positive degree": "positive",
    "equative degree": "equative",
    "indicative and subjunctive": "indicative subjunctive",
    "indicative/subjunctive": "indicative subjunctive",
    "second/third-person": "second-person third-person",
    "singular/plural": "singular plural",
    "dual/plural": "dual plural",
    "collective or in the plural": "collective in-plural",
    "in the plural": "in-plural",
    "(with savrtsobi)": "with-savrtsobi",
    "plural and definite singular": ["plural", "definite singular"],
    "feminine singular & neuter plural": ["feminine singular", "neuter plural"],
    "partitive/illative": "partitive illative",
    "oblique/nominative": "oblique nominative",
    "nominative/vocative/dative/strong genitive":
    ["nominative vocative dative", "strong genitive"],
    "non-attributive": "not-attributive",
    "attributive use": "attributive",
    "nominative/vocative/instrumental":
    "nominative vocative instrumental",
    "nominative/vocative/strong genitive/dative":
    ["nominative vocative dative", "strong genitive"],
    "nominative/vocative/dative": "nominative vocative dative",
    "accusative/genitive/partitive/illative":
    "accusative genitive partitive illative",
    "nominative/vocative/accusative/genitive":
    "nominative vocative accusative genitive",
    "accusative/genitive/locative": "accusative locative genitive",
    "accusative/genitive/dative/instrumental":
    "accusative genitive dative instrumental",
    "accusative/genitive/dative": "accusative genitive dative",
    "accusative/genitive": "accusative genitive",
    "masculine/feminine/neuter": "masculine feminine neuter",
    "feminine/neuter/masculine": "masculine feminine neuter",
    "feminine/neuter": "feminine neuter",
    "present participle and present tense": ["present participle", "present"],
    "present participle and gerund": ["present participle", "gerund"],
    "all-gender": "",
    "all-case": "",
    "accusative/dative": "accusative dative",
    "accusative-singular": "accusative singular",
    "accusative-genitive": "accusative genitive",
    "dative/locative/instrumental": "dative locative instrumental",
    "dative/vocative/locative": "dative vocative locative",
    "dative/prepositional": "dative prepositional",
    "dative and ablative": "dative ablative",
    "nominative/vocative/dative and strong genitive":
    ["nominative vocative dative", "strong genitive"],
    "nominative/vocative/accusative":
    "nominative vocative accusative",
    "nominative/vocative": "nominative vocative",
    "nominative/oblique": "nominative oblique",
    "nominative/locative": "nominative locative",
    "nominative/instrumental": "nominative instrumental",
    "nominative/genitive/dative/accusative":
    "nominative genitive dative accusative",
    "nominative/genitive/dative": "nominative genitive dative",
    "nominative/genitive/accusative/vocative":
    "nominative genitive accusative vocative",
    "nominative/genitive/accusative":
    "nominative genitive accusative",
    "nominative/dative": "nominative dative",
    "nominative/accusative/vocative/instrumental":
    "nominative accusative vocative instrumental",
    "nominative/accusative/vocative": "nominative accusative vocative",
    "nominative/accusative/nominative/accusative":
    "nominative accusative",
    "nominative/accusative/nominative": "nominative accusative",
    "nominative/accusative/locative": "nominative accusative locative",
    "nominative/accusative/genitive/dative":
    "nominative accusative genitive dative",
    "nominative/accusative/genitive": "nominative accusative genitive",
    "nominative/accusative/genitive": "nominative accusative genitive",
    "nominative/accusative/dative": "nominative accusative dative",
    "nominative/accusative": "nominative accusative",
    "perfective/imperfective": "perfective imperfective",
    "animate/inanimate": "animate inanimate",
    "locative/vocative": "locative vocative",
    "prospective/agentive": "prospective agentive",
    "genitive/accusative": "genitive accusative",
    "singular/duoplural": "singular duoplural",
    "first/second/third-person":
    "first-person second-person third-person",
    "first/third/third-person": "first-person third-person",
    "first/second/second-person": "first-person second-person",
    "first/third-person": "first-person third-person",
    "first-person/second-person": "first-person second-person",
    "first-person/third-person": "first-person third-person",
    "first-person singular/third-person singular":
    "first-person third-person singular",
    "first-person singular/third-person plural":
    ["first-person singular", "third-person plural"],
    "affirmative/negative": "affirmative negative",
    "first-, second-, third-person singular subjunctive present":
    "first-person second-person third-person singular subjunctive present",
    "first-, second- and third-person singular present indicative":
    "first-person second-person third-person singular present indicative",
    "first- and third-person": "first-person third-person",
    "female equivalent": "feminine",
    "direct/oblique/vocative": "direct oblique vocative",
    "definite/plural": "definite plural",
    "singular definite and plural": ["singular definite", "plural"],
    "agent noun": "agent",
    "third active infinitive": "third-infinitive active",
    "third passive infinitive": "third-infinitive passive",
    "British spelling": "UK",
    "Urdu spelling": "urdu-spelling",
    "Urdu spelling of": "urdu-spelling alt-of",
    "eye dialect": "pronunciation-spelling",
    "enclitic and proclitic": "enclitic proclitic",
    "Devanagari script form of": "alt-of Devanagari",
    "obsolete form of": "alt-of obsolete",
    "(hence past tense)": "past",
    "(suffix conjugation)": "suffix",
    "(suffix conjugation)": "prefix",
    "(nós)": "with-nos",
    "(eu)": "with-eu",
    "(vós)": "with-vós",
    "(vos)": "with-vos",
    "(voseo)": "with-voseo",
    "(tu)": "with-tu",
    "(tú)": "with-tú",
    "(eles)": "with-eles",
    "(elas)": "with-elas",
    "(vocês)": "with-vocês",
    "(usted)": "with-usted",
    "(ustedes)": "with-ustedes",
    "(yo)": "with-yo",
    "(ele, ela, also used with tu and você?)":
    "with-ele with-ela with-tu with-você",
    "(eles and elas, also used with vocês and others)":
    "with-eles with-elas with-vocês with-others",
    "(você)": "with-você",
    "(hiri)": "with-hiri",
    "(hura)": "with-hura",
    "(zuek)": "with-zuek",
    "(vós, sometimes used with vocês)": "with-vós with-vocês",
    "(gij)": "with-gij",
    "(tu, sometimes used with você)": "with-tu with-você",
    "(\u00e9l, ella, also used with usted)":
    "with-él with-ella with-usted",
    "(ellos, ellas, also used with ustedes)":
    "with-ellos with-ellas with-ustedes",
    "(nosotros, nosotras)": "with-nosotros with-nosotras",
    "(vosotros, vosotras)": "with-vosotros with-vosotras",
    "(vosotros or vosotras)": "with-vosotros with-vosotras",
    "(ele and ela, also used with você and others)":
    "with-ele with-ela with-você with-others",
    "(ele, ela, also used with tu and você)":
    "with-ele with-ela with-tu with-você",
    "former reform[s] only": "",
    "no construct forms": "no-construct-forms",
    "no nominative plural": "no-nominative-plural",
    "no supine": "no-supine",
    "no perfect": "no-perfect",
    "no genitive": "no-genitive",
    "no superlative": "no-superlative",
    "no comparative": "no-comparative",
    "no plural": "no-plural",
    "no singular": "plural-only",
    "not comparable": "not-comparable",
    "plurale tantum": "plurale-tantum",
    "possessive suffix": "possessive suffix",
    "possessive determiner": "possessive determiner",
    "pronominal state": "pronominal-state",
    "nominal state": "nominal-state",
    "form i": "form-i",
    "form ii": "form-ii",
    "form iii": "form-iii",
    "form iv": "form-iv",
    "form v": "form-v",
    "form vi": "form-vi",
    "form vii": "form-vii",
    "form viii": "form-viii",
    "form ix": "form-ix",
    "form x": "form-x",
    "form xi": "form-xi",
    "form xii": "form-xii",
    "form xiii": "form-xiii",
    "form iq": "form-iq",
    "form iiq": "form-iiq",
    "form iiiq": "form-iiiq",
    "form ivq": "form-ivq",
    "class 1": "class-1",
    "class 1a": "class-1a",
    "class 2": "class-2",
    "class 2a": "class-2a",
    "class 3": "class-3",
    "class 4": "class-4",
    "class 5": "class-5",
    "class 6": "class-6",
    "class 7": "class-7",
    "class 8": "class-8",
    "class 9": "class-9",
    "class 10": "class-10",
    "class 11": "class-11",
    "class 12": "class-12",
    "class 13": "class-13",
    "class 14": "class-14",
    "class 15": "class-15",
    "class 16": "class-16",
    "class 17": "class-17",
    "m-wa class": "m-wa-class",
    "m-mi class": "m-mi-class",
    "u class": "u-class",
    "ki-vi class": "ki-vi-class",
    "first declension": "first-declension",
    "second declension": "second-declension",
    "third declension": "third-declension",
    "fourth declension": "fourth-declension",
    "fifth declension": "fifth-declension",
    "first conjugation": "first-conjugation",
    "second conjugation": "second-conjugation",
    "third conjugation": "third-conjugation",
    "fourth conjugation": "fourth-conjugation",
    "fifth conjugation": "fifth-conjugation",
    "sixth conjugation": "sixth-conjugation",
    "seventh conjugation": "seventh-conjugation",
    "stress pattern 1": "stress-pattern-1",
    "stress pattern 2": "stress-pattern-2",
    "stress pattern 3": "stress-pattern-3",
    "stress pattern 3a": "stress-pattern-3a",
    "stress pattern 3b": "stress-pattern-3b",
    "stress pattern 4": "stress-pattern-4",
    "type p": "type-p",
    "type u": "type-u",
    "type up": "type-up",
    "type a": "type-a",
    "ordinal form of": "ordinal form-of",
    "the ordinal form of the number": "ordinal form-of",
    "the ordinal form of": "ordinal form-of",
    "the ordinal of": "ordinal form-of",
    "the ordinal number corresponding to the cardinal number":
    "ordinal form-of",
    "the ordinal form of the cardinal number": "ordinal form-of",
    "the ordinal number": "ordinal form-of",
    "used in the form": "used-in-the-form",
    "upper case": "upper-case",
    "lower case": "lower-case",
    "mixed case": "mixed-case",
    "verb form i": "verb-form-i",
    "verb form ii": "verb-form-ii",
    "pi'el construction": "pi'el-construction",
    "pa'el construction": "pa'el-construction",
    "hif'il construction": "hif'il-construction",
    "hitpa'el construction": "hitpa'el-construction",
    "pu'al construction": "pu'al-construction",
    "nif'al construction": "nif'al-construction",
    "huf'al construction": "huf'al-construction",
    "verbal noun": "verbal-noun",
    "abstract noun": "abstract-noun",
    "genitive as verbal noun": "genitive verbal-noun",
    "genitive singular as substantive": "genitive singular substantive",
    "female names": "feminine proper-noun",
    "proper name": "proper-noun",
    "proper noun": "proper-noun",
    "proper nouns": "proper-noun",
    "usually in the": "usually",
    "non-scientific usage": "non-scientific",
    "krama inggil": "krama-inggil",
    "McCune-Reischauer chŏn": "McCune-Reischauer-chŏn",
    "gender indeterminate": "gender-neutral",
    "singular only": "singular singular-only",
    "plural only": "plural plural-only",
    "imperative only": "imperative-only",
    "in general sense": "broadly",
    "by extension": "broadly",
    "by metonymy": "metonymically",
    "by semantic narrowing": "narrowly",
    "by semantic widening": "broadly",
    "strict sense": "strict-sense",
    "baby talk": "baby-talk",
    "middle infinitive": "middle-infinitive",
    "first infinitive": "first-infinitive",
    "second infinitive": "second-infinitive",
    "second active infinitive": "second-infinitive active",
    "second passive infinitive": "second-infinitive passive",
    "third infinitive": "third-infinitive",
    "third active infinitive": "third-infinitive active",
    "third passive infinitive": "third-infinitive passive",
    "fourth infinitive": "fourth-infinitive",
    "fifth infinitive": "fifth-infinitive",
    "subjunctive I": "subjunctive-I",
    "subjunctive II": "subjunctive-II",
    "morse code": "morse-code",
    "with odd-syllable stems": "with-odd-syllable-stems",
    "old orthography": "archaic",
    "Brazilian ortography": "Brazilian",
    "European ortography": "European",
    "with noun phrase": "with-noun-phrase",
    "contracted dem-form": "contracted-dem-form",
    "contractions": "contraction",
    "Yale cen": "Yale-cen",
    "subjective pronoun": "subjective-pronoun",
    "revised jeon": "revised-jeon",
    "form used before": "archaic",
    "front vowel harmony variant": "front-vowel",
    "romanization of": "alt-of romanization",
    "romanisation of": "alt-of romanization",
    "archaic spelling of": "alt-of archaic",
    "obsolete typography of": "alt-of obsolete",
    "obsolete spelling of": "alt-of obsolete",
    "rare spelling of": "alt-of rare",
    "superseded spelling of": "alt-of archaic",
    "pronunciation spelling of": "alt-of pronunciation-spelling",
    "eye dialect spelling of": "alt-of pronunciation-spelling",
    "alternative or obsolete spelling of":
    "alt-of obsolete alternative",
    "obsolete and rare": "obsolete rare",
    "American spelling": "US",
    "Canadian spelling": "Canada",
    "alternative name of": "alt-of alternative",
    "nonstandard spelling of": "alt-of nonstandard",
    "US standard spelling of": "alt-of US standard",
    "US spelling of": "alt-of US",
    "alternative typography of": "alt-of alternative",
    "polytonic spelling of": "alt-of polytonic",
    "variant of": "alt-of alternative",
    "uncommon spelling of": "alt-of uncommon",
    "alternative typographic spelling of": "alt-of alternative",
    "alternative spelling of": "alt-of alternative",
    "alternative form of": "alt-of alternative",
    "alternative term for": "alt-of alternative",
    "alternative stem of": "alt-of stem alternative",
    "alternative letter-case form of": "alt-of",
    "medieval spelling of": "alt-of obsolete",
    "post-1930s Cyrillic spelling of": "alt-of standard",
    "pre-1918 spelling of": "alt-of obsolete",
    "Switzerland and Liechtenstein standard spelling of":
    "alt-of Switzerland Liechtenstein standard",
    "form removed with the spelling reform of 2012; superseded by":
    "alt-of dated",
    "excessive spelling of": "alt-of excessive",
    "exaggerated degree of": "alt-of exaggerated",
    "defective spelling of": "alt-of misspelling",
    "alternative verbal noun of": "alt-of verbal-noun",
    "alternative conjugation of": "alt-of alternative",
    "abbreviation of": "alt-of abbreviation",
    "eclipsed form of": "alt-of abbreviation eclipsis",
    "apocopic form of": "alt-of abbreviation apocope",
    "h-prothesized form of": "alt-of prothesis",
    "acronym of": "alt-of abbreviation",
    "initialism of": "alt-of abbreviation initialism",
    "contraction of": "alt-of abbreviation contraction",
    "IUPAC 3-letter abbreviation of": "alt-of abbreviation",
    "praenominal abbreviation of": "alt-of abbreviation praenominal",
    "ellipsis of": "alt-of ellipsis abbreviation",
    "clipping of": "alt-of clipping abbreviation",
    "X-system spelling of": "alt-of X-system",
    "H-system spelling of": "alt-of H-system",
    "Pinyin transcription of": "alt-of Pinyin",
    "Rōmaji transcription of": "alt-of Rōmaji",
    "visual rendering of Morse code for":
    "alt-of visual-rendering morse-code",
    "soft mutation of": "alt-of soft",
    "Non-Oxford British English standard spelling of":
    "alt-of nonstandard UK",
    "Nil standard spelling of": "alt-of UK standard",
    "nasal mutation of": "alt-of nasal mutation",
    "mixed mutation of": "alt-of mixed mutation",
    "aspirate mutation of": "alt-of aspirate mutation",
    "misspelling of": "alt-of misspelling",
    "deliberate misspelling of": "alt-of misspelling deliberate",
    "common misspelling of": "alt-of misspelling",
    "misconstruction of": "alt-of misconstruction",
    "Latin spelling of": "alt-of latin",
    "Late Anglo-Norman spelling of": "alt-of Anglo-Norman",
    "Jawi spelling of": "alt-of Jawi",
    "Hanja form of": "alt-of Hanja",
    "Hanja form? of": "alt-of Hanja",
    "Hán tự form of": "alt-of han-tu",
    "Glagolitic spelling of": "alt-of Glagolitic",
    "front vowel variant of": "alt-of front-vowel",
    "front-vowel variant of": "alt-of front-vowel",
    "euphemistic spelling of": "alt-of euphemistic",
    "euphemistic reading of": "alt-of euphemistic",
    "Cyrillic spelling of": "alt-of Cyrillic",
    "Cyrillic spelling": "Cyrillic",
    "British standard spellingh of": "alt-of UK standard",
    "British and Canada standard spelling of":
    "alt-of UK Canada standard",
    "Britain and Ireland standard spelling of":
    "alt-of Britain Ireland standard",
    "Britain and New Zealand standard spelling of":
    "alt-of Britain New-Zealand standard",
    "Britain and Canada spelling of": "alt-of Britain Canada",
    "Baybayin spelling of": "alt-of Baybayin",
    "Arabic spelling of": "alt-of Arabic",
    "Formerly standard spelling of": "alt-of archaic",
    "informal spelling of": "alt-of informal",
    "Yañalif spelling of": "alt-of Yañalif",
    "traditional orthography spelling of": "alt-of traditional",
    "Taraškievica spelling of": "alt-of Taraškievica",
    "Baybayin spelling of": "alt-of Baybayin",
    "Post-1930s Cyrillic spelling of": "alt-of Cyrillic",
    "Britain spelling of": "alt-of Britain",
    "linguistically informed spelling of": "alt-of literary",
    "Chinese spelling of": "alt-of China",
    "Mongolian spelling of": "alt-of Mongolia",
    "Leet spelling of": "alt-of Leet",
    "plural of": "form-of plural",
    "combining form of": "in-compounds form-of",
    "compound of": "compound-of",
    "compound of gerund of": "compound-of",
    "compound of imperative (noi form) of": "compound-of",
    "compound of imperative (tu form) of": "compound-of",
    "compound of imperative (vo form) of": "compound-of",
    "compound of imperative (voi form) of": "compound-of",
    "compound of imperative of": "compound-of",
    "compound of indicative present of": "compound-of",
    "compound of masculine plural past participle of": "compound-of",
    "compound of past participle of": "compound-of",
    "compound of present indicative of": "compound-of",
    "compound of plural past participle of": "compound-of",
    "compound of second-person singular imperative of": "compound-of",
    "compound of the gerund of": "compound-of",
    "compound of the imperfect": "compound-of",
    "compound of the infinitive": "compound-of",
    "synonym of": "synonym-of",
    "same as": "synonym-of",
    "topicalized form of": "topic form-of",
    "form of": "form-of",
    "inflected form of": "form-of",
    "lenited form of": "lenition form-of",
    "humurous": "humorous",
    "humourous": "humorous",
    "sarcasm": "sarcastic",
    "ironic": "humorous",
    "figuratively or literally": "figuratively literally",
    "figuratively and literary": "figuratively literary",
    "figuative": "figuratively",
    "humorously": "humorous",
    "jocular": "humorous",
    "humorous or euphemistic": "humorous euphemistic",
    "may sound impolite": "possibly impolite",
    "northern dialects": "dialectal",
    "archaic or loosely": "archaic broadly",
    "archaic or poetic": "archaic poetic",
    "archaic or dialectal": "archaic dialectal",
    "archaic or literary": "archaic literary",
    "most dialects": "dialectal",
    "most dialects of Ripuarian": "dialectal",
    "some dialects": "dialectal",
    "some compounds": "idiomatic in-compounds",
    "used attributively": "attributive",
    "used predicatively": "predicative",
    "used substatively": "substantive",
    "unofficial spelling": "nonstandard",
    "capitalised": "capitalized",
    "rhetorical question": "rhetoric",
    "old-fashioned": "dated",
    "rarely used": "rare",
    "rarely": "rare",
    "now rare": "archaic",
    "fixed expressions": "idiomatic",
    "formulaic": "idiomatic",
    "several set phrases": "idiomatic",
    "now colloquial": "colloquial",
    "now colloquial and nonstandard": "colloquial nonstandard",
    "colloquial or Min Nan": "colloquial",
    "colloquial or jargon": "colloquial jargon",
    "Wiktionary and WMF jargon": "jargon Internet",
    "colloquially": "colloquial",
    "fossil word": "archaic",
    "brusque": "impolite",
    "verbs": "verb",
    "local use": "regional",
    "more generally": "broadly",
    "loosely": "broadly",
    "broad sense": "broadly",
    "hypocoristic": "familiar",
    "familiar or childish": "familiar childish",
    "to a male": "addressee-masculine",
    "to a female": "addressee-masculine",
    "hyperbolic": "excessive",
    "18th century": "obsolete",
    "9th century": "obsolete",
    "17th century": "obsolete",
    "10th century": "obsolete",
    "16th century": "obsolete",
    "14th century": "obsolete",
    "12th century": "obsolete",
    "post-classical": "obsolete",
    "early 20th century": "archaic",
    "20th century": "dated",
    "mid-20th century": "dated",
    "mid-19th century": "obsolete",
    "before 20th century": "obsolete",
    "19th to 20th century": "archaic",
    "15th century": "obsolete",
    "11th century": "obsolete",
    "until early 20th century": "obsolete",
    "since the 16th century": "dated",
    "late 16th century": "obsolete",
    "late 14th century": "obsolete",
    "in usage until 20th century": "obsolete",
    "in the 17th century": "obsolete",
    "in the 16 th century": "obsolete",
    "in Scots until the seventeenth century": "obsolete",
    "in 10th century": "obsolete",
    "early 17th century": "obsolete",
    "chiefly 18th century": "obsolete",
    "chiefly 12th century": "obsolete",
    "before 16th century": "obsolete",
    "attested in the 16th century": "obsolete",
    "5th century": "obsolete",
    "19th to early 20th century": "obsolete",
    "19th-mid 20th century": "obsolete",
    "19 the century": "obsolete",
    "19th-early 20th century": "obsolete",
    "19th century": "obsolete",
    "1776-19th century": "obsolete",
    "15th-16th century": "obsolete",
    "collectively": "collective",
    "collective or singulative": "collective singulative",
    "used formally in Spain": "Spain",
    "nouns": "noun",
    "with the particle lai": "with-lai",
    "adjectives": "adjective",
    "adj": "adjective",
    "adj.": "adjective",
    "augmentatives": "augmentative",
    "pejoratives": "pejorative",
    "pejorative or colloquial": "pejorative colloquial",
    "non-standard since 2012": "nonstandard",
    "colloquialism": "colloquial",
    "non-standard since 1917": "nonstandard",
    "conditional mood": "conditional",
    "figurative": "figuratively",
    "reciprocal": "reflexive",
    "compound words": "compound",
    "form of address": "term-of-address",
    "term of address": "term-of-address",
    "as a term of address": "term-of-address",
    "direct address": "term-of-address",
    "face-to-face address term": "term-of-address",
    "address": "term-of-address",
    "endearingly": "endearing",
    "elliptically": "ellipsis",
    "elegant": "formal",  # Elegant or Formal Thai
    "nonce word": "neologism",
    "neologism or slang": "neologism slang",
    "attributively": "attributive",
    "poetic term": "poetic",
    "poetic meter": "poetic",
    "in certain phrases": "in-certain-phrases",
    "deprecated template usage": "deprecated-template",
    "diacritical mark": "diacritic",
    "inflection of": "form-of",
    "mainland China": "Mainland-China",
    "rhyming slang": "slang",
    "prison slang": "slang",
    "criminal slang": "slang",
    "fandom slang": "slang",
    "furry fandom": "slang",
    "manga fandom slang": "slang",
    "real estate slang": "slang",
    "gay slang": "slang",
    "urban slang": "slang",
    "lolspeak": "humorous Internet",
    "Usenet": "Internet",
    "one-termination adjective": "one-termination",
    "two-termination adjective": "two-termination",
    "three-termination adjective": "three-termination",
    "semelefactive": "semelfactive",
    "invariant": "invariable",
    "followed by to": "with-to",
    "taking a to-infinitive": "with-to with-infinitive",
    "with bare infinitive": "with-infinitive",
    "direct object": "direct-object",
    "transitive with of": "transitive-with-of",
    "with of": "with-of",
    "with on": "with-on",
    "with down": "with-down",
    "with up": "with-up",
    "with a personal pronoun": "with-personal-pronoun",
    "with an indirect object": "with-indirect-object",
    "with comparatives": "with-comparative",
    "etc.": "usually",
    "regardless of gender": "gender-neutral",
    "ditransitive for the second object": "ditransitive",
    "number": "numeral",
    "+ 3rd-pers.": "with-third-person",
    "Historical": "historical",
    "antiquity": "historical",
    "ideophone": "ideophonic",
    "Alsatian (Low Alemannic German)": "Alsatian",
    "all sects": "",
}

# This mapping is applied to full descriptions before splitting by comma
xlat_descs_map = {
    "with there, or dialectally it, as dummy subject": "with-dummy-subject",
    "+ location in inessive, adessive + vehicle in elative":
    "with-inessive with-adessive with-elative",
    "+ accusative +, Genitive": "with-accusative with-genitive",
    "with genitive, instrumental or dative case":
    "with-genitive with-instrumental with-dative",
}

valid_tags = set([
    "-i",   # Japanese inflection type
    "-na",  # Japanese inflection type
    "-nari",  # Japanese inflection type
    "-tari",  # Japanese inflection type
    "abbreviation",
    "abessive",
    "ablative",
    "absolute",   # XXX Swedish at least ???
    "absolutive",
    "abstract",
    "abstract-noun",
    "accent/glottal",
    "accusative",
    "active",
    "addressee-female",
    "addressee-masculine",
    "adessive",
    "adjectival",
    "adjective",
    "adnominal",
    "adverb",
    "adverbial",
    "affirmative",
    "agent",
    "agentive",
    "alienable",
    "allative",
    "also",
    "alt-of",
    "alternative",
    "ambitransitive",
    "analytic",
    "anaphorically",
    "animate",
    "aorist",
    "apocope",
    "archaic",
    "article",
    "aspirate",
    "attributive",
    "augmentative",
    "augmented",
    "autonomous",
    "auxiliary",
    "baby-talk",
    "broadly",
    "būdinys",
    "cangjie-input",
    "canonical",  # Used to mark the canonical word from from the head tag
    "capitalized",
    "capitalized",
    "cardinal",
    "catenative",
    "causal-final",
    "causative",
    "causative",
    "chiefly",
    "childish",
    "class-1",
    "class-10",
    "class-10a",
    "class-11",
    "class-12",
    "class-13",
    "class-14",
    "class-15",
    "class-16",
    "class-17",
    "class-1a",
    "class-2",
    "class-2a",
    "class-3",
    "class-4",
    "class-5",
    "class-6",
    "class-7",
    "class-8",
    "class-9",
    "class-9a",
    "classifier",
    "clipping",
    "clitic",
    "cohortative",
    "collective",
    "colloquial",
    "comitative",
    "common",
    "comparable",
    "comparative",
    "complete",
    "composition",
    "compound",
    "compound-of",
    "conditional",
    "conjunct",
    "conjunctive",
    "connegative",
    "construct",
    "contemplative",
    "continuously",
    "contracted",
    "contracted-dem-form",
    "contraction",
    "coordinating",
    "copulative",
    "cot-caught-merger",
    "countable",
    "da-infinitive",
    "dated",
    "dative",
    "debitive",
    "defective",
    "definite",
    "definition",
    "definitive",  # XXX is this used same as "definite", opposite indefinite?
    "deictically",
    "delative",
    "deliberate",
    "demonstrative",
    "dependent",
    "deprecated-template",
    "derogatory",
    "determiner",
    "deuterotonic",
    "diacritic",
    "dialectal",
    "diminutive",
    "direct",
    "direct-object",
    "directional",
    "distal",
    "ditransitive",
    "dual",       # two in number
    "duoplural",  # two or more in number
    "durative",
    "eclipsis",
    "economics",
    "elative",
    "ellipsis",
    "emphatic",
    "empty-gloss",
    "enclitic",
    "endearing",
    "epic",
    "epicene",
    "equative",
    "ergative",
    "error-lua-exec",
    "error-lua-timeout",
    "error-unknown-tag",
    "error-unrecognized-form",
    "especially",
    "essive",
    "essive-formal",
    "essive-instructive",
    "essive-modal",
    "ethnic",
    "eumhun",
    "euphemism",
    "euphemistic",
    "exaggerated",
    "excessive",
    "exclusive",
    "expletive",
    "expressively",
    "familiar",
    "feminine",
    "fifth-conjugation",
    "fifth-declension",
    "fifth-infinitive",
    "figuratively",
    "first-conjugation",
    "first-declension",
    "first-infinitive",
    "first-person",
    "form-i",
    "form-ii",
    "form-iii",
    "form-iiiq",
    "form-iiq",
    "form-iq",
    "form-iv",
    "form-ivq",
    "form-ix",
    "form-of",
    "form-v",
    "form-vi",
    "form-vii",
    "form-viii",
    "form-x",
    "form-xi",
    "form-xii",
    "form-xiii",
    "formal",
    "four-corner",
    "fourth-conjugation",
    "fourth-declension",
    "fourth-infinitive",
    "fourth-person",
    "frequentative",
    "front-vowel",
    "future",
    "gender-neutral",
    "genitive",
    "gerund",
    "han-tu",
    "hangeul",
    "hellenism",
    "hif'il-construction",
    "historic",
    "historical",
    "hitpa'el-construction",
    "honorific",
    "huf'al-construction",
    "humble",
    "humorous",
    "hypercorrect",
    "hypothetic",
    "ideophonic",
    "idiomatic",
    "illative",
    "imperative",
    "imperative-only",
    "imperfect",
    "imperfective",
    "impersonal",
    "impolite",
    "in-certain-phrases",
    "in-compounds",
    "in-plural",
    "inalienable",
    "inanimate",
    "inclusive",
    "indeclinable",
    "indefinite",
    "independent",
    "indicative",
    "inessive",
    "infinitive",
    "infix",
    "informal",
    "initialism",
    "instructive",
    "instrumental",
    "interrogative",
    "intransitive",
    "invariable",
    "ionic",
    "irregular",
    "jargon",
    "jussive",
    "ki-vi-class",
    "krama",
    "krama-inggil",
    "krama-ngoko",
    "kyūjitai",
    "latin",
    "lative",
    "lenition",
    "letter",
    "literally",
    "literary",
    "locative",
    "lower-case",
    "m-mi-class",
    "m-wa-class",
    "mainly",
    "masculine",
    "material",
    "medial",
    "mediopassive",
    "metaphoric",
    "metonymically",
    "middle",
    "middle-infinitive",
    "mildly",
    "misconstruction",
    "misspelling",
    "mixed",
    "mixed-case",
    "modal",
    "modern",
    "morpheme",
    "morse-code",
    "mostly",
    "multiple-possession",
    "mutated",
    "mutation",
    "name",
    "narrowly",
    "nasal",
    "natural",
    "negative",
    "neologism",
    "neuter",
    "next",
    "ngoko",
    "nif'al-construction",
    "no-comparative",
    "no-construct-forms",
    "no-genitive",
    "no-nominative-plural",
    "no-perfect",
    "no-plural",
    "no-senses",
    "no-superlative",
    "no-supine",
    "nominal",
    "nominal-state",
    "nominalization",
    "nominative",
    "non-past",
    "non-scientific",
    "nonstandard",
    "nonvirile",
    "not-attributive",
    "not-comparable",
    "not-predicative",
    "noun",
    "now",
    "numeral",
    "objective",
    "oblique",
    "obsolete",
    "offensive",
    "often",
    "one-termination",
    "only",
    "onomatopoeia",
    "optative",
    "ordinal",
    "pa'el-construction",
    "participle",
    "particle",
    "partitive",
    "partner",
    "passive",
    "past",
    "paucal",
    "pausal",
    "pejorative",
    "perfect",
    "perfective",
    "person",
    "personal",
    "phoneme",
    "physical",
    "pi'el-construction",
    "place",
    "pluperfect",
    "plural",     # depending on language, two or more / three or more
    "plural-only",
    "plurale-tantum",
    "poetic",
    "polite",
    "polytonic",
    "positive",
    "possessed",
    "possessive",
    "possibly",
    "postpositive",
    "potential",
    "praenominal",
    "predicative",
    "prefix",
    "prepositional",
    "present",
    "preterite",
    "previous",
    "proclitic",
    "progressive",
    "prolative",
    "pronominal",
    "pronominal-state",
    "pronoun",
    "pronunciation-spelling",
    "proper-noun",
    "proscribed",
    "prospective",
    "prothesis",
    "prototonic",
    "proximal",
    "pu'al-construction",
    "quadral",
    "quotative",
    "radical",
    "radical+strokes",
    "rare",
    "reconstruction",
    "reduplicated",
    "reflexive",
    "regional",
    "relational",
    "relative",
    "revised-jeon",
    "rhetoric",
    "romanization",
    "root",
    "sarcastic",
    "second-conjugation",
    "second-declension",
    "second-infinitive",
    "second-person",
    "semelfactive",
    "sequence",
    "sequential",
    "seventh-conjugation",
    "shinjitai",
    "short",
    "si-perfective",
    "simple",
    "simplified",
    "single-possession",
    "singular",
    "singular-only",
    "singulative",  # Individuation of a collective or mass noun
    "sixth-conjugation",
    "slang",
    "slur",
    "soft",
    "sometimes",
    "somewhat",
    "specifically",
    "standard",
    "stative",
    "stem",
    "stress-pattern-1",
    "stress-pattern-2",
    "stress-pattern-3",
    "stress-pattern-3a",
    "stress-pattern-3b",
    "stress-pattern-4",
    "stressed",
    "strict-sense",
    "strokes",
    "strong",
    "subject",
    "subjective",
    "subjective-pronoun",
    "subjunctive",
    "subjunctive-I",
    "subjunctive-II",
    "sublative",
    "subordinating",
    "substantive",
    "suffix",
    "superessive",
    "superlative",
    "supine",
    "suppletive",
    "surnames",
    "suru",  # Japanese verb inflection type
    "syllable-final",
    "syllable-initial",
    "synonym-of",
    "taboo",
    "term-of-address",
    "terminative",
    "third-conjugation",
    "third-declension",
    "third-infinitive",
    "third-person",
    "three-termination",
    "topic",
    "traditional",
    "transcription",
    "transgressive",
    "transitive",
    "transitive-with-of",
    "translative",
    "transliteration",
    "trial",
    "two-termination",
    "type-a",
    "type-p",
    "type-u",
    "type-up",
    "typography",
    "u-class",
    "unaugmented",
    "uncommon",
    "uncountable",
    "unstressed",
    "upper-case",
    "urdu-spelling",
    "used-in-the-form",
    "usually",
    "vav-consecutive",
    "verb",
    "verb-form-i",
    "verb-form-ii",
    "verbal-noun",
    "virile",
    "visual-rendering",
    "vocative",
    "volitive",
    "vulgar",
    "weak",
    "weak-verb",
    "with-a",
    "with-ablative",
    "with-absolutive",
    "with-accusative",
    "with-adessive",
    "with-adjective",
    "with-allative",
    "with-an",
    "with-avec",
    "with-ce",
    "with-che",
    "with-comparative",
    "with-con",
    "with-conditional",
    "with-da",
    "with-dative",
    "with-de",
    "with-di",
    "with-down",
    "with-ela",
    "with-elas",
    "with-elative",
    "with-ele",
    "with-eles",
    "with-ella",
    "with-ellas",
    "with-ellos",
    "with-en",
    "with-eu",
    "with-for",
    "with-genitive",
    "with-gij",
    "with-hiri",
    "with-hura",
    "with-illative",
    "with-in",
    "with-indicative",
    "with-indirect-object",
    "with-inessive",
    "with-infinitive",
    "with-instrumental",
    "with-järgi",
    "with-kala",
    "with-lai",
    "with-locative",
    "with-meel",
    "with-negation",
    "with-nos",
    "with-nosotras",
    "with-nosotros",
    "with-noun",
    "with-noun-phrase",
    "with-number",
    "with-objective",
    "with-odd-syllable-stems",
    "with-of",
    "with-on",
    "with-optative",
    "with-others",
    "with-partitive",
    "with-past-participle",
    "with-per",
    "with-personal-pronoun",
    "with-por",
    "with-possessive-suffix",
    "with-pour",
    "with-prepositional",
    "with-present",
    "with-savrtsobi",
    "with-sein",
    "with-simple",
    "with-su",
    "with-subjunctive",
    "with-sur",
    "with-dummy-subject",
    "with-third-person",
    "with-third-infinitive-elative",
    "with-third-infinitive-illative",
    "with-to",
    "with-translative",
    "with-tu",
    "with-tú",
    "with-up",
    "with-usted",
    "with-ustedes",
    "with-você",
    "with-vocês",
    "with-vos",
    "with-voseo",
    "with-vosotras",
    "with-vosotros",
    "with-välja",
    "with-vós",
    "with-yo",
    "with-zuek",
    "with-à",
    "with-él",
    "without-noun",
    "zhuyin",
    "æ-tensing",
])
