# https://sv.wiktionary.org/wiki/Wiktionary:Stilguide#Ordklassrubriken
POS_DATA = {
    "Substantiv": {"pos": "noun"},
    "Adjektiv": {"pos": "adj"},
    "Verb": {"pos": "verb"},
    "Adverb": {"pos": "adv"},
    "Räkneord": {"pos": "num"},
    "Preposition": {"pos": "prep"},
    "Konjunktion": {"pos": "conj"},
    "Interjektion": {"pos": "intj"},
    "Pronomen": {"pos": "pron"},
    "Artikel": {"pos": "article"},
    "Verbpartikel": {"pos": "particle", "tags": ["verb"]},
    "Partikel": {"pos": "particle"},
    "Talesätt": {"pos": "proverb"},
    "Ordspråk": {"pos": "proverb"},
    "Förkortning": {"pos": "abbrev", "tags": ["abbreviation"]},
    "Affix": {"pos": "affix"},
    "Förled": {"pos": "prefix", "tags": ["morpheme"]},
    "Efterled": {"pos": "suffix", "tags": ["morpheme"]},
    "Fras": {"pos": "phrase"},
    "Tecken": {"pos": "symbol"},
    "Kod": {"pos": "symbol"},
    "Cirkumposition": {"pos": "circumpos"},
    "Postposition": {"pos": "postp"},
    "Räknemarkör": {"pos": "counter"},
    "Infinitivmärke": {"pos": "verb", "tags": ["infinitive"]},
    "Transkription": {"pos": "romanization"},
}
