# https://tr.wiktionary.org/wiki/Vikisözlük:Girdilerin_biçimi#Söz_türü
POS_DATA = {
    "Ad": {"pos": "noun"},
    "Adıl": {"pos": "pron"},
    "Bağlaç": {"pos": "conj"},
    "Belirteç": {"pos": "adv"},
    "Eylem": {"pos": "verb"},
    "Edat": {"pos": "particle"},
    "Ön ad": {"pos": "adj"},
    "Özel ad": {"pos": "name"},
    "Sayı adı": {"pos": "num"},
    "Ünlem": {"pos": "intj"},
    "Ek eylem": {"pos": "verb", "tags": ["auxiliary"]},
    "Ön Ek": {"pos": "prefix", "tags": ["morpheme"]},
    "Son ek": {"pos": "suffix", "tags": ["morpheme"]},
    "Harf": {"pos": "character", "tags": ["letter"]},
    "Hece": {"pos": "syllable"},
    "Kısaltma": {"pos": "abbrev", "tags": ["abbreviation"]},
    "Noktalama işareti": {"pos": "punct", "tags": ["punctuation"]},
    "Sembol": {"pos": "symbol"},
    "Atasözü": {"pos": "proverb"},
    "Deyim": {"pos": "phrase", "tags": ["idiomatic"]},
    # "Mecaz"
    "İfade": {"pos": "phrase"},
    "Han karakteri": {"pos": "character", "tags": ["han"]},
    "Hanzi": {"pos": "character", "tags": ["hanzi"]},
    "Kanji": {"pos": "character", "tags": ["kanji"]},
    "Hanja": {"pos": "character", "tags": ["Hanja"]},
    "Romanizasyon": {"pos": "romanization"},
}
