from wiktextract.config import POSSubtitleData

POS_TITLES: POSSubtitleData = {
    "аббревиатура": {"pos": "abbrev"},
    "глагол": {"pos": "verb"},
    "деепричастие": {"pos": "gerund"},
    "имя собственное": {"pos": "name"},
    "имя, собственное": {"pos": "name"},
    "междометие": {"pos": "interj"},
    "префикс": {"pos": "prefix"},
    "префиксоид": {"pos": "prefix"},
    "прилагательное": {"pos": "adj"},
    "суффикс": {"pos": "suffix"},
    "существительное": {"pos": "noun"},
    "устойчивое сочетание": {"pos": "phrase"},
    "наречие": {"pos": "adv"},
}

POS_TEMPLATE_NAMES: POSSubtitleData = {
    "abbrev": {"pos": "abbrev", "tags": ["abbreviation"]},
    "adv": {"pos": "adv"},
    "affix": {"pos": "affix"},
    "article": {"pos": "article"},
    "conj": {"pos": "conj"},
    "interj": {"pos": "intj"},
    "noun": {"pos": "noun"},
    "onomatop": {"pos": "onomatopeia", "tags": ["onomatopoeic"]},
    "part": {"pos": "particle"},
    "phrase": {"pos": "phrase"},
    "predic": {"pos": "adj"},
    "prep": {"pos": "prep"},
    "suffix": {"pos": "suffix"},
    "буква": {"pos": "character"},
    "гидроним": {"pos": "name"},
    "гл": {"pos": "verb"},
    "дее": {"pos": "verb", "tags": ["participle", "gerund"]},
    "деепр": {"pos": "verb", "tags": ["participle", "gerund"]},
    "мест": {"pos": "pron"},
    "нар": {"pos": "adv"},
    "падежи": {"pos": "noun"},
    "послелог": {"pos": "postp"},
    "посл": {"pos": "postp"},
    "прил": {"pos": "adj"},
    "прич": {"pos": "verb", "tags": ["participle"]},
    "союз": {"pos": "conj"},
    "сущ": {"pos": "noun"},
    "существительное": {"pos": "noun"},
    "топоним": {"pos": "name"},
    "фам": {"pos": "name"},
    "част": {"pos": "particle"},
    "числ": {"pos": "num"},
}

LINKAGE_TITLES: dict[str, str] = {
    "антонимы": "antonyms",
    "анаграммы": "anagrams",
    "варианты": "variants",
    "гиперонимы": "hypernyms",
    "гипонимы": "hyponyms",
    "дериваты": "derived",
    "меронимы": "meronyms",
    "синонимы": "synonyms",
    "согипонимы": "coordinate_terms",
    "холонимы": "holonyms",
}
