POS_DATA = {
    "artigo": {"pos": "article"},
    "adjetivo": {"pos": "adj"},
    "advérbio": {"pos": "adv"},
    "conjunção": {"pos": "conj"},
    "interjeição": {"pos": "intj"},
    "numeral": {"pos": "num"},
    "partícula": {"pos": "particle"},
    "preposição": {"pos": "prep"},
    "posposição": {"pos": "postp"},
    "pronome": {"pos": "pron"},
    "substantivo": {"pos": "noun"},
    "berbo": {"pos": "verb"},
    "forma de substantivo": {"pos": "noun", "tags": ["form-of"]},
    "forma verbal": {"pos": "verb", "tags": ["form-of"]},
    "locução substantiva": {"pos": "phrase", "tags": ["substantive"]},
    "locução adjetiva": {"pos": "phrase", "tags": ["adjectival"]},
    "locução adverbial": {"pos": "phrase", "tags": ["adverbial"]},
    "locução prepositiva": {"pos": "phrase", "tags": ["prepositional"]},
    "expressão": {"pos": "phrase"},
    "abreviatura": {"pos": "abbrev", "tags": ["abbreviation"]},
    "contração": {"pos": "contraction", "tags": ["contraction"]},
    "prefixo": {"pos": "prefix", "tags": ["morpheme"]},
    "sufixo": {"pos": "suffix", "tags": ["morpheme"]},
    "sigla": {"pos": "abbrev", "tags": ["abbreviation"]},
    "símbolo": {"pos": "symbol"},
    "substantivo próprio": {"pos": "name"},
    "adjetivo próprio": {"pos": "adj", "tags": ["name"]},
    "forma de adjetivo": {"pos": "adj", "tags": ["form-of"]},
    "letra": {"pos": "character", "tags": ["letter"]},
    "transliteração": {"pos": "romanization"},
    "numeral ordinal": {"pos": "adj"},
    "numeral cardinal": {"pos": "adj"},
    "ordinal equivalente": {"pos": "adj"},
    "locução interjetiva": {"pos": "phrase", "tags": ["interjection"]},
    "adjetivo numeral distributivo": {
        "pos": "adj",
        "tags": ["distributive", "numeral"],
    },
    "forma de pronome": {"pos": "pron", "tags": ["form-of"]},
    "advérbio numeral": {"pos": "adv", "tags": ["numeral"]},
}


LINKAGE_SECTIONS = {
    "antônimos": "antonyms",
    "antônimo": "antonyms",
    "antónimo": "antonyms",
    "antónimos/antônimos": "antonyms",
    "sinônimos": "synonyms",
    "sinônimo": "synonyms",
    "sinónimos/sinônimos": "synonyms",
    "sinónimos": "synonyms",
    "sinónimo": "synonyms",
    "verbetes derivados": "derived",
    "verbete derivado": "derived",
    "formas alternativas": "synonyms",
    "anagramas": "anagrams",
    "anagrama": "anagrams",
    "hiperônimo": "hypernyms",
    "hiperônimos": "hypernyms",
    "hiperónimos": "hypernyms",
    "termos derivados": "derived",
    "grafia antiga": "synonyms",
    "diminutivo": "synonyms",
    "diminutivos": "synonyms",
    "termos relacionados": "related",
    "variante ortográfica": "synonyms",
    "verbetes relacionados": "related",
    "entradas relacionadas": "related",
    "hipônimos": "hyponyms",
    "hiponímias": "hyponyms",
    "ortografias obsoletas": "synonyms",
    "superlativo": "synonyms",
    "outros verbetes": "related",
    "cardinal equivalente": "synonyms",
    "aumentativo": "synonyms",
}

LINKAGE_TAGS = {
    "grafia antiga": ["obsolete"],
    "diminutivo": ["diminutive"],
    "diminutivos": ["diminutive"],
    "ortografias obsoletas": ["obsolete"],
    "superlativo": ["superlative"],
    "aumentativo": ["augmentative"],
}
