POS_DATA = {
    "Artigo": {"pos": "article"},
    "Adjetivo": {"pos": "adj"},
    "Advérbio": {"pos": "adv"},
    "Conjunção": {"pos": "conj"},
    "Interjeição": {"pos": "intj"},
    "Numeral": {"pos": "num"},
    "Partícula": {"pos": "particle"},
    "Preposição": {"pos": "prep"},
    "Posposição": {"pos": "postp"},
    "Pronome": {"pos": "pron"},
    "Substantivo": {"pos": "noun"},
    "Verbo": {"pos": "verb"},
    "Forma verbal": {"pos": "verb", "tags": ["form-of"]},
    "Locução substantiva": {"pos": "phrase", "tags": ["substantive"]},
    "Locução adjetiva": {"pos": "phrase", "tags": ["adjectival"]},
    "Locução adverbial": {"pos": "phrase", "tags": ["adverbial"]},
    "Locução prepositiva": {"pos": "phrase", "tags": ["prepositional"]},
    "Expressão": {"pos": "phrase"},
    "Abreviatura": {"pos": "abbrev", "tags": ["abbreviation"]},
    "Contração": {"pos": "contraction", "tags": ["contraction"]},
    "Prefixo": {"pos": "prefix", "tags": ["morpheme"]},
    "Sufixo": {"pos": "suffix", "tags": ["morpheme"]},
    "Sigla": {"pos": "abbrev", "tags": ["abbreviation"]},
    "Símbolo": {"pos": "symbol"},
}
