# https://en.wiktionary.org/wiki/Template:zh-pron
ZH_PRON_TAGS = {
    "Pe̍h-ōe-jī-like": "POJ",
    "Pe̍h-ōe-jī": "POJ",
    "Pha̍k-fa-sṳ": "Phak-fa-su",
    "Tongyong Pinyin": "Tongyong-Pinyin",
    "Phofsit Daibuun": "Phofsit-Daibuun",
    "Hagfa Pinyim": "Hagfa-Pinyim",
    "Min Dong": "Min-Dong",
    "Guangdong Romanization": "Guangdong-Romanization",
    "Gwoyeu Romatzyh": "Gwoyeu-Romatsyh",
    "Wiktionary": "Wiktionary-specific",
    "Middle Chinese": "Middle-Chinese",
    "Sinological IPA": "Sinological-IPA",
    "old-style": "dated",
    "Cantonese Pinyin": ["Cantonese", "Pinyin"],
    "Wade–Giles": "Wade-Giles",
    "Baxter–Sagart": "Baxter-Sagart",
    "PFS": "Phak-fa-su",
    "Tâi-lô": "Tai-lo",
    "Zhuyin": "Bopomofo",
    "BUC": "Foochow-Romanized",
    "Standard Cantonese": "Standard-Cantonese",
    "Standard Chinese": "Standard-Chinese",
    "Beijing Mandarin": ["Beijing", "Mandarin"],
    "Beijing dialect": ["Beijing", "dialectal"],
    "Guangzhou–Hong Kong": ["Guangzhou", "Hong Kong"],
    "Mainland China": "Mainland-China",
    "Mainland literary": ["Mainland-China", "literary"],
    "Northern Sixian": ["Northern", "Sixian"],
    "Southern Sixian": ["Southern", "Sixian"],
    "variant in Taiwan": ["Taiwan", "variant"],
    "Mainland Standard": ["Mainland-China", "standard"],
    "Mainland standard": ["Mainland-China", "standard"],
    "Mainland variant": ["Mainland-China", "variant"],
    "Mainland": "Mainland-China",
    "Taiwan standard": "Taiwan",
    "Standard Mainland": ["Mainland-China", "standard"],
    "Standard Taiwan": ["Taiwan", "standard"],
    "Standard in Mainland": ["Mainland-China", "standard"],
    "standard in Mainland": ["Mainland-China", "standard"],
    "Standard in Taiwan": ["Taiwan", "standard"],
    "standard in Taiwan": ["Taiwan", "standard"],
    "variant in Mainland": ["Mainland-China", "variant"],
    "Taiwan variant": ["Taiwan", "variant"],
    "colloquial variant": ["colloquial", "variant"],
    "dated variant in Mainland": ["dated", "variant", "Mainland-China"],
    "historical variant in Mainland": [
        "historical",
        "variant",
        "Mainland-China",
    ],
    "alternative in Mainland": ["alternative", "Mainland-China"],
    "alternative standard reading in Taiwan": [
        "alternative",
        "standard",
        "Taiwan",
    ],
    "basilect vernacular": "vernacular",
    "colloquial Beijing dialect variant": [
        "colloquial",
        "Beijing",
        "dialectal",
        "variant",
    ],
    "colloquial in Mainland": ["colloquial", "Mainland-China"],
    "colloquial reading": "colloquial",
    "colloquial variant from other Mandarin dialects": [
        "colloquial",
        "variant",
        "Mandarin",
        "dialectal",
    ],
    "colloquial variant in Beijing": ["colloquial", "variant", "Beijing"],
    "originally Beijing dialect": ["Beijing", "dialectal"],
    "now standard in Taiwan": ["standard", "Taiwan"],
    "dialectal variant": ["dialectal", "variant"],
    "common Mainland variant": ["common", "Mainland-China", "variant"],
    "common alternative": ["common", "alternative"],
    "common colloquial variant": ["common", "colloquial", "variant"],
    "common in Taiwan": ["common", "Taiwan"],
    "common nonstandard variant": ["common", "nonstandard", "variant"],
    "non-standard": "nonstandard",
    "common variant in Mainland": ["common", "variant", "Mainland-China"],
    "common variant in Taiwan": ["common", "variant", "Taiwan"],
    "common variant": ["common", "variant"],
    "common vernacular reading": ["common", "vernacular"],
    "dated variant in Taiwan": ["dated", "variant", "Taiwan"],
    "dated variant": ["dated", "variant"],
    "historical variant": ["historical", "variant"],
    "literary in Mainland": ["literary", "Mainland-China"],
    "regional variant": ["regional", "variant"],
    "literary variant in Mainland": ["literary", "variant", "Mainland-China"],
    "literary variant in Taiwan": ["literary", "variant", "Taiwan"],
    "rare variant": ["rare", "variant"],
    "erhua-ed": "Erhua",
    "non-standard variant in Mainland": [
        "nonstandard",
        "variant",
        "Mainland-China",
    ],
    "non-standard variant": ["nonstandard", "variant"],
    "nonstandard in Mainland": ["nonstandard", "Mainland-China"],
    "nonstandard variant in Mainland": [
        "nonstandard",
        "variant",
        "Mainland-China",
    ],
    "nonstandard variant": ["nonstandard", "variant"],
    "obsolete in Mainland": ["obsolete", "Mainland-China"],
    "rare literary variant": ["rare", "literary", "variant"],
    "Taiwan literary": ["Taiwan", "literary"],
    "Min Nan-influenced": "Min-Nan",
    "Wuhan dialect": ["Wuhan", "dialectal"],
    "dated Beijing dialect": ["dated", "Beijing", "dialectal"],
    "imitating Min Nan": ["imitating", "Min-Nan"],
    "imitating Sichuanese": ["imitating", "Sichuanese"],
    "imitating Tianjin dialect": ["imitating", "Tianjin", "dialectal"],
    "vernacular variant": ["vernacular", "variant"],
    "Kienning Colloquial Romanized": "Kienning-Colloquial-Romanized",
    "Min Bei": "Min-Bei",
    "KCR": "Kienning-Colloquial-Romanized",
    "Min Nan": "Min-Nan",
    "Old Chinese": "Old-Chinese",
    "Scuanxua Ladinxua Xin Wenz": "Latinxua-Sin-Wenz",
    "Sichuanese Pinyin": ["Sichuanese", "Pinyin"],
    "Northern Min": "Min-Bei",
    "Southern Pinghua": "Southern-Pinghua",
    "Jyutping++": "Jyutping-plusplus",
    "Nanjing Pinyin": ["Nanjing", "Pinyin"],
    "MiniDict": "MiniDict",
    "Puxian Min": "Puxian-Min",
    "Pouseng Ping'ing": "Pouseng-Ping'ing",
    "Kunshan": "Kunshan",
    "Eastern Min": "Min-Dong",
    "Guanzhong Pinyin": ["Guanzhong", "Pinyin"],
    "Yongchun": "Yongchun",
    "Jiading": "Jiading",
    "Leizhou Pinyin": ["Leizhou", "Pinyin"],
    "Longyan": "Longyan",
    "Nanning Pinghua": ["Nanning", "Southern-Pinghua"],
    "Zhoushan": "Zhoushan",
    "Xianyou": "Xianyou",
    "Hengyang": "Hengyang",
    "Shaoxing": "Shaoxing",
    "Southern Min": "Min-Nan",
    "Jiaxing": "Jiaxing",
    "Wugniu": "Wugniu",
    "Báⁿ-uā-ci̍": "Hinghwa-Romanized",
    "Wiktionary Romanisation": ["Wiktionary-specific", "romanization"],
    "Guancheng": "Guancheng",
    "Songjiang": "Songjiang",
    "Changzhou": "Changzhou",
    "Putian": "Putian",
    "HRS": "Hakka-Romanization-System",
    "Hakka Romanization System": "Hakka-Romanization-System",
    "Hanyu Pinyin": "Pinyin",
    "toneless final syllable variant": "toneless-final-syllable-variant",
    "Bàng-uâ-cê": "Foochow-Romanized",
}
